-- Seed Exercise Library for Cross Health PT Clinic Management
-- 100 exercises organized by body region with clinical-grade instructions
-- Compatible with exercise_library table schema

-- Clear existing seed data to avoid duplicates
DELETE FROM exercise_library WHERE is_active = true;

-- ============================================================
-- CERVICAL SPINE (Exercises 1-8)
-- ============================================================

INSERT INTO exercise_library (name, description, instructions, body_part, difficulty, equipment, sets, reps, duration_seconds, tags, is_active) VALUES

('Chin Tucks', 'Deep cervical flexor activation and forward head posture correction', 'Patient seated or standing with upright posture. Instruct patient to retract the chin posteriorly, creating a "double chin," while maintaining a level gaze. Avoid cervical flexion or extension. Hold retracted position for 5-10 seconds. Cue: "Pull your chin straight back as if making a double chin." Ensure the movement is pure retraction without tilting the head.', ARRAY['cervical spine'], 'beginner', ARRAY['none'], 3, 15, NULL, ARRAY['strengthening', 'posture', 'deep cervical flexors'], true),

('Cervical Rotation AROM', 'Active range of motion for cervical rotation to restore mobility', 'Patient seated with upright posture, shoulders relaxed. Slowly rotate the head to look over one shoulder, moving to end range as tolerated without pain. Hold 2-3 seconds at end range. Return to midline. Repeat to the opposite side. One repetition = both sides. Avoid compensatory trunk rotation or shoulder elevation.', ARRAY['cervical spine'], 'beginner', ARRAY['none'], 3, 10, NULL, ARRAY['mobility', 'range of motion'], true),

('Cervical Lateral Flexion AROM', 'Active range of motion for cervical sidebending', 'Patient seated with upright posture, shoulders relaxed and level. Slowly tilt the ear toward the ipsilateral shoulder without rotating the head or elevating the shoulder. Move to comfortable end range. Hold 2-3 seconds. Return to neutral. Repeat to the opposite side. Cue: "Bring your ear toward your shoulder, not your shoulder to your ear."', ARRAY['cervical spine'], 'beginner', ARRAY['none'], 3, 10, NULL, ARRAY['mobility', 'range of motion'], true),

('Upper Trapezius Stretch', 'Sustained stretch of the upper trapezius muscle to address cervicogenic tension', 'Patient seated with upright posture. Anchor the involved side by sitting on the hand or gripping the chair seat. Laterally flex the head away from the involved side. Apply gentle overpressure with the contralateral hand placed on the temporal region. Hold for 30 seconds. The patient should feel a stretch along the lateral neck into the upper trapezius. Avoid rotation during the stretch.', ARRAY['cervical spine', 'shoulder'], 'beginner', ARRAY['none'], 3, 1, 30, ARRAY['stretching', 'flexibility', 'muscle tension'], true),

('Levator Scapulae Stretch', 'Targeted stretch of the levator scapulae muscle', 'Patient seated with upright posture. Anchor the involved side by gripping the chair seat. Rotate the head approximately 45 degrees away from the involved side, then flex the chin toward the contralateral axilla. Apply gentle overpressure with the hand on the occiput. Hold for 30 seconds. The patient should feel a stretch at the posterolateral neck/superior medial scapular border. Avoid shrugging the contralateral shoulder.', ARRAY['cervical spine'], 'beginner', ARRAY['none'], 3, 1, 30, ARRAY['stretching', 'flexibility'], true),

('Cervical Isometric Resistance — Multi-Directional', 'Isometric cervical strengthening in flexion, extension, lateral flexion, and rotation', 'Patient seated with upright posture. Place the palm against the forehead and press the head into the hand without allowing movement (isometric). Hold 5-10 seconds. Repeat with hand on the occiput (extension), each temporal region (lateral flexion), and each side of the jaw (rotation). 6 directions total constitute one set. Resistance should be submaximal, approximately 50-75% effort. Monitor for symptom reproduction.', ARRAY['cervical spine'], 'intermediate', ARRAY['none'], 3, 6, NULL, ARRAY['strengthening', 'isometric', 'cervical stability'], true),

('Supine Cervical Flexion with Chin Tuck (Craniocervical Flexion)', 'Progressive deep cervical flexor endurance training', 'Patient supine without pillow. Perform a chin tuck (craniocervical flexion) and gently lift the head 1 inch off the surface while maintaining the tucked position. Hold for 5-10 seconds. The movement should be a subtle nod, not a full neck curl. If the superficial SCM and anterior scalenes dominate, reduce the hold time. Progress hold duration as endurance improves. This targets the longus colli and longus capitis.', ARRAY['cervical spine'], 'intermediate', ARRAY['none'], 3, 10, NULL, ARRAY['strengthening', 'deep cervical flexors', 'endurance'], true),

('Cervical Retraction with Extension (McKenzie)', 'Combined cervical retraction and extension for discogenic cervical pathology', 'Patient seated with upright posture. First perform a full chin tuck (retraction). While maintaining the retraction, slowly extend the cervical spine by looking upward toward the ceiling. Hold 2-3 seconds at end range. Return to the retracted position first, then relax. Contraindicated in cervical stenosis or if extension reproduces radicular symptoms. Monitor for peripheralization.', ARRAY['cervical spine'], 'intermediate', ARRAY['none'], 3, 10, NULL, ARRAY['mobility', 'McKenzie', 'extension'], true),

-- ============================================================
-- THORACIC SPINE (Exercises 9-12)
-- ============================================================

('Thoracic Foam Roll Extension', 'Thoracic spine extension mobilization over a foam roller', 'Patient supine with the foam roller positioned horizontally at the mid-thoracic spine. Cross arms over the chest or support the head with interlocked fingers. Allow the thoracic spine to extend over the roller while maintaining abdominal bracing to isolate motion to the thoracic segments. Hold 3-5 seconds. Reposition the roller one segment superiorly or inferiorly and repeat. Avoid hyperextending the lumbar spine.', ARRAY['thoracic spine'], 'beginner', ARRAY['foam roller'], 3, 10, NULL, ARRAY['mobility', 'extension', 'self-mobilization'], true),

('Open Book Thoracic Rotation', 'Thoracic rotation mobilization in sidelying', 'Patient sidelying with hips and knees flexed to 90 degrees, a pillow between the knees. Arms extended forward, palms together. Keeping the knees stacked and the pelvis stable, slowly rotate the top arm open toward the opposite side, following the hand with the eyes. Allow the thoracic spine to rotate while the lumbar spine remains neutral. Hold 3-5 seconds at end range. Return slowly. Repeat on the opposite side.', ARRAY['thoracic spine'], 'beginner', ARRAY['pillow'], 3, 10, NULL, ARRAY['mobility', 'rotation'], true),

('Seated Thoracic Rotation with Dowel', 'Active thoracic rotation with lumbar stabilization', 'Patient seated on a stool or bench with feet flat on the floor. Hold a dowel or broomstick across the shoulders behind the neck. Without moving the pelvis, rotate the trunk as far as comfortable to one side. Hold 2-3 seconds. Return to center. Repeat to the opposite side. Ensure the hips remain square and the motion occurs through the thoracic spine. Cue: "Rotate your ribcage, not your hips."', ARRAY['thoracic spine'], 'beginner', ARRAY['dowel'], 3, 10, NULL, ARRAY['mobility', 'rotation'], true),

('Prone Y-T-W Raises', 'Scapular stabilizer and lower trapezius strengthening with thoracic extension', 'Patient prone on a table or stability ball with arms hanging. Raise both arms into a Y position (thumbs up, arms at 120 degrees abduction) squeezing the scapulae together. Hold 3 seconds. Lower. Repeat in T position (90 degrees abduction) and W position (elbows bent, shoulders externally rotated). 1 rep = all three positions. Use light weights (1-3 lbs) to progress. Avoid excessive lumbar extension.', ARRAY['thoracic spine', 'shoulder', 'scapula'], 'intermediate', ARRAY['none', 'light dumbbells'], 3, 8, NULL, ARRAY['strengthening', 'scapular stability', 'postural'], true),

-- ============================================================
-- LUMBAR SPINE (Exercises 13-22)
-- ============================================================

('Pelvic Tilts', 'Gentle lumbar segmental mobility and transversus abdominis activation', 'Patient supine with knees bent, feet flat on the surface. Instruct the patient to flatten the lower back against the surface by gently contracting the abdominals and posteriorly tilting the pelvis. Hold for 5 seconds. Relax and allow the natural lumbar lordosis to return. Cue: "Imagine pulling your belly button toward your spine and pressing your low back flat." Breathing should remain normal throughout.', ARRAY['lumbar spine', 'core'], 'beginner', ARRAY['none'], 3, 15, NULL, ARRAY['mobility', 'core activation', 'motor control'], true),

('Cat-Cow Stretch', 'Rhythmic lumbar and thoracic segmental mobility exercise', 'Patient in quadruped (hands and knees) with hands under shoulders and knees under hips. Inhale while allowing the abdomen to drop toward the floor, extending the spine and lifting the head (cow). Exhale while rounding the spine upward toward the ceiling, tucking the chin and pelvis (cat). Move slowly and rhythmically between positions, coordinating with breath. Each cycle = 1 rep. Focus on segmental movement rather than global motion.', ARRAY['lumbar spine', 'thoracic spine'], 'beginner', ARRAY['none'], 3, 10, NULL, ARRAY['mobility', 'warm-up', 'segmental motion'], true),

('Prone Press Up (McKenzie Extension)', 'Repeated lumbar extension in prone for centralization of discogenic symptoms', 'Patient prone with hands positioned by the shoulders as in a push-up position. Press the upper body upward by straightening the arms while keeping the pelvis and hips in contact with the surface. Allow the lumbar spine to extend passively. Hold 2-3 seconds at end range. Lower slowly. Monitor for centralization of symptoms (peripheral symptoms moving toward midline = positive response). Contraindicated if symptoms peripheralize or in the presence of spondylolisthesis.', ARRAY['lumbar spine'], 'beginner', ARRAY['none'], 3, 10, NULL, ARRAY['mobility', 'McKenzie', 'extension', 'centralization'], true),

('Bird Dog', 'Lumbar stabilization with contralateral limb loading', 'Patient in quadruped with neutral spine. Simultaneously extend the right arm forward and left leg backward, maintaining a neutral spine and level pelvis. Hold 3-5 seconds. Return to starting position. Alternate to the opposite arm/leg. Avoid rotating the trunk or hiking the hip. Cue: "Imagine balancing a glass of water on your lower back." The lumbar spine should not move during limb excursion. Progress by increasing hold time or adding light ankle/wrist weights.', ARRAY['lumbar spine', 'core'], 'beginner', ARRAY['none'], 3, 10, NULL, ARRAY['core stability', 'strengthening', 'motor control'], true),

('Dead Bug', 'Supine core stabilization with reciprocal limb movement', 'Patient supine with arms extended toward the ceiling and hips/knees flexed to 90 degrees. Maintain a posterior pelvic tilt (flatten the low back). Slowly lower the right arm overhead and extend the left leg toward the floor simultaneously. Do not allow the lumbar spine to arch away from the surface. Return to starting position. Alternate sides. If the low back lifts, reduce the range of excursion. Progress by adding resistance or slowing the tempo.', ARRAY['lumbar spine', 'core'], 'intermediate', ARRAY['none'], 3, 10, NULL, ARRAY['core stability', 'strengthening', 'motor control'], true),

('Double Knee to Chest Stretch', 'General lumbar flexion stretch to reduce paraspinal tension', 'Patient supine. Bring both knees toward the chest and grasp behind the thighs or over the shins. Gently pull the knees toward the chest until a comfortable stretch is felt in the lower back. Hold for 30 seconds. Breathe normally. Avoid pulling on the tibial tuberosities. This position also reduces intradiscal pressure and may relieve facet-mediated symptoms.', ARRAY['lumbar spine'], 'beginner', ARRAY['none'], 3, 1, 30, ARRAY['stretching', 'flexibility', 'lumbar flexion'], true),

('Lumbar Rotation Stretch (Supine Trunk Rotation)', 'Rotational stretch for lumbar paraspinals and obliques', 'Patient supine with knees bent, feet flat. Keeping the shoulders on the surface, slowly allow both knees to fall to one side toward the floor. Hold for 20-30 seconds. Return to center. Repeat to the opposite side. Arms may be in a T position for stability. The stretch should be felt in the lower back and lateral trunk. Avoid forcing range; allow gravity to provide the stretch.', ARRAY['lumbar spine'], 'beginner', ARRAY['none'], 3, 1, 30, ARRAY['stretching', 'flexibility', 'rotation'], true),

('McGill Curl-Up', 'Evidence-based anterior core strengthening with spinal-sparing technique', 'Patient supine with one knee bent and one leg straight. Place the hands under the lumbar spine to maintain neutral lordosis. Brace the abdominals and lift only the head and shoulders off the surface (do not flex the lumbar spine). Hold for 8-10 seconds. The lumbar spine should not flatten or flex during the movement. This differs from a traditional crunch by preserving the neutral spine. Described by Dr. Stuart McGill as a spine-sparing alternative.', ARRAY['lumbar spine', 'core'], 'intermediate', ARRAY['none'], 3, 10, NULL, ARRAY['strengthening', 'core stability', 'McGill'], true),

('Side-Lying Hip Abduction (for Lateral Core)', 'Lateral stabilization chain activation in sidelying', 'Patient sidelying with the bottom knee bent for stability and the trunk in neutral alignment. Lift the top leg approximately 30-45 degrees with the toes pointed slightly downward (to bias gluteus medius). Hold 3 seconds. Lower with control. Do not roll the pelvis backward. This exercise also challenges lateral trunk stabilization. Progress by adding an ankle weight or resistance band above the knee.', ARRAY['lumbar spine', 'hip', 'glutes'], 'beginner', ARRAY['none', 'ankle weight'], 3, 15, NULL, ARRAY['strengthening', 'hip stability', 'lateral chain'], true),

-- ============================================================
-- CORE / ABDOMINAL (Exercises 23-28)
-- ============================================================

('Plank (Forearm)', 'Anterior and global core stabilization in a prone position', 'Begin in a prone position propped on the forearms and toes. Align the body in a straight line from the head to the heels. Engage the core by bracing the abdominals (as if preparing for a punch to the stomach). Do not allow the hips to sag or pike upward. Maintain neutral cervical alignment. Hold for the prescribed duration. Cue: "Squeeze your glutes, brace your abs, and keep your body in a straight plank." Progress by increasing hold time in 10-second increments.', ARRAY['core', 'lumbar spine'], 'intermediate', ARRAY['none'], 3, 1, 30, ARRAY['core stability', 'strengthening', 'endurance'], true),

('Side Plank', 'Lateral core stabilization targeting the quadratus lumborum and obliques', 'Patient sidelying propped on the bottom forearm with the elbow under the shoulder. Lift the hips off the surface, creating a straight line from head to feet. The top arm may rest on the hip or extend toward the ceiling. Hold for the prescribed duration. Do not allow the hips to drop or rotate. Modification: Bend the bottom knee and prop from the knee instead of the feet. One of McGill''s "Big 3" exercises for spinal stability.', ARRAY['core', 'lumbar spine', 'hip'], 'intermediate', ARRAY['none'], 3, 1, 20, ARRAY['core stability', 'strengthening', 'McGill'], true),

('Transversus Abdominis Activation (Drawing-In Maneuver)', 'Isolated deep core activation for motor control training', 'Patient supine with knees bent, or in quadruped. Instruct the patient to gently draw the lower abdomen inward toward the spine without moving the pelvis, ribs, or spine. Hold for 10 seconds while breathing normally. Palpate medial to the ASIS for transversus abdominis contraction (should feel a gentle tensioning, not a bulge). Avoid substitution with rectus abdominis, obliques, or breath holding. This is a low-level activation (20-30% MVC). Use pressure biofeedback unit (Stabilizer) at 40 mmHg baseline if available.', ARRAY['core'], 'beginner', ARRAY['none', 'pressure biofeedback unit'], 3, 10, NULL, ARRAY['core stability', 'motor control', 'deep core'], true),

('Pallof Press', 'Anti-rotation core stabilization exercise', 'Patient standing perpendicular to a cable column or anchored resistance band at chest height. Hold the handle with both hands at the sternum. Press the arms straight forward, resisting the rotational pull of the band/cable. Hold 3-5 seconds with arms extended. Return to the chest. The core must resist rotation throughout. Maintain a neutral spine and avoid shifting the weight toward the anchor. Progress by increasing resistance or performing from a half-kneeling position.', ARRAY['core', 'lumbar spine'], 'intermediate', ARRAY['resistance band', 'cable machine'], 3, 10, NULL, ARRAY['core stability', 'anti-rotation', 'functional'], true),

('Supine March (Core Stability)', 'Dynamic core stability with alternating hip flexion', 'Patient supine with knees bent, feet flat. Establish a neutral spine with gentle abdominal bracing. Slowly lift one foot off the surface, flexing the hip to 90 degrees while maintaining a stable pelvis and neutral lumbar spine. Lower the foot. Alternate sides. The lumbar spine should not extend or rotate during the movement. Palpate the abdominals to confirm they remain engaged. This is a progression from static TA activation toward dynamic challenges.', ARRAY['core', 'hip'], 'beginner', ARRAY['none'], 3, 10, NULL, ARRAY['core stability', 'motor control'], true),

('Ab Wheel Rollout (or Stability Ball Rollout)', 'Advanced anterior core strengthening with eccentric loading', 'Patient kneeling with hands on an ab wheel or stability ball. Slowly roll forward, extending the arms and hips while maintaining a rigid trunk. Do not allow the lumbar spine to hyperextend. Roll out only as far as the patient can control without losing neutral spine. Return to the starting position by flexing at the hips and contracting the core. This is an advanced exercise; ensure the patient can hold a plank for 60+ seconds before progressing here.', ARRAY['core', 'lumbar spine', 'shoulder'], 'advanced', ARRAY['ab wheel', 'stability ball'], 3, 8, NULL, ARRAY['strengthening', 'core stability', 'advanced'], true),

-- ============================================================
-- SHOULDER (Exercises 29-42)
-- ============================================================

('Pendulum Exercises (Codman)', 'Passive/active-assistive shoulder mobilization for early post-operative or acute phase rehabilitation', 'Patient standing, flexed at the waist approximately 60-90 degrees, supporting the uninvolved side on a table. The involved arm hangs freely. Initiate gentle pendular motion by shifting body weight — forward/backward, side-to-side, and in small clockwise/counterclockwise circles. The shoulder musculature should remain relaxed; motion comes from trunk sway. Each direction for 30-60 seconds. May hold a 1-2 lb weight to provide gentle traction. Indicated post rotator cuff repair, adhesive capsulitis, or proximal humerus fracture per protocol.', ARRAY['shoulder'], 'beginner', ARRAY['none', 'light dumbbells'], 3, 10, NULL, ARRAY['mobility', 'warm-up', 'post-surgical'], true),

('Shoulder External Rotation with Resistance Band', 'Strengthens the infraspinatus and teres minor (rotator cuff external rotators)', 'Patient standing or seated with the elbow flexed to 90 degrees and held firmly against the side (a towel roll between the elbow and trunk may be used as a tactile cue). Grasp the resistance band anchored at waist height on the opposite side. Rotate the forearm outward away from the body, keeping the elbow pinned to the side. Slowly return with a 3-second eccentric phase. Do not allow the elbow to drift anteriorly or the trunk to rotate. Progress band resistance as tolerated.', ARRAY['shoulder', 'rotator cuff'], 'intermediate', ARRAY['resistance band'], 3, 12, NULL, ARRAY['strengthening', 'rotator cuff'], true),

('Shoulder Internal Rotation with Resistance Band', 'Strengthens the subscapularis (rotator cuff internal rotator)', 'Patient standing with elbow flexed to 90 degrees, held at the side. Grasp the resistance band anchored at waist height on the ipsilateral side. Rotate the forearm inward across the body against the resistance. Slowly return with controlled eccentric phase. Maintain the elbow position at the side throughout. A towel roll between the elbow and trunk can be used to maintain proper positioning. Avoid compensatory trunk rotation.', ARRAY['shoulder', 'rotator cuff'], 'intermediate', ARRAY['resistance band'], 3, 12, NULL, ARRAY['strengthening', 'rotator cuff'], true),

('Wall Slides (Serratus Punch Variation)', 'Scapular upward rotation training and serratus anterior activation', 'Patient standing facing a wall with forearms on the wall in a "W" position (elbows bent, shoulders at 90 degrees). Slowly slide the arms upward into a "Y" position while maintaining forearm contact with the wall. At the top, actively protract the scapulae (push into the wall). Slowly slide back to the W position. Maintain upright posture and avoid compensatory lumbar extension or rib flare. Cue: "Slide up the wall and push through at the top."', ARRAY['shoulder', 'scapula'], 'beginner', ARRAY['none'], 3, 10, NULL, ARRAY['mobility', 'scapular stability', 'serratus anterior'], true),

('Shoulder Flexion AAROM with Cane/Wand', 'Active-assistive shoulder flexion using the uninvolved arm to assist', 'Patient supine holding a cane or wand with both hands, shoulder-width apart. Using the uninvolved arm to power the movement, raise both arms overhead into flexion as far as tolerated. Hold 3-5 seconds at end range. Lower slowly. The involved arm should be relaxed and allowing the uninvolved arm to do the work. This is indicated when active motion is limited or post-surgical precautions restrict active muscle use.', ARRAY['shoulder'], 'beginner', ARRAY['cane', 'dowel'], 3, 10, NULL, ARRAY['mobility', 'active-assistive', 'post-surgical'], true),

('Shoulder AROM Flexion (Supine to Standing Progression)', 'Active shoulder flexion through available range', 'Begin supine if gravity-eliminated motion is needed. Raise the arm into full flexion overhead with the thumb pointing up. Lower with control. Progress to seated, then standing as strength allows. Maintain scapulohumeral rhythm — watch for compensatory scapular hiking or trunk lean. If painful arc exists between 60-120 degrees, note and modify. Full ROM = 180 degrees of flexion.', ARRAY['shoulder'], 'beginner', ARRAY['none'], 3, 10, NULL, ARRAY['mobility', 'range of motion', 'strengthening'], true),

('Sidelying External Rotation', 'Gravity-resisted rotator cuff external rotation strengthening', 'Patient sidelying on the uninvolved side with the involved elbow bent to 90 degrees, a towel roll under the arm for proper positioning. Hold a light dumbbell (1-5 lbs). Slowly rotate the forearm upward toward the ceiling. Hold 2 seconds. Lower with a 3-second eccentric phase. Avoid rolling the trunk backward. This isolates the infraspinatus/teres minor with gravitational resistance. A gold-standard exercise in rotator cuff rehabilitation.', ARRAY['shoulder', 'rotator cuff'], 'intermediate', ARRAY['light dumbbells'], 3, 12, NULL, ARRAY['strengthening', 'rotator cuff', 'isolation'], true),

('Scapular Retraction (Squeeze)', 'Rhomboid and middle trapezius strengthening for postural correction', 'Patient seated or standing with upright posture, arms at sides. Squeeze the shoulder blades together and downward as if placing them in your back pockets. Hold 5 seconds. Relax. Avoid shrugging the shoulders. Cue: "Pinch your shoulder blades together and down." This addresses scapular protraction commonly associated with upper crossed syndrome and forward head posture. Progress by adding resistance band rows.', ARRAY['shoulder', 'scapula', 'thoracic spine'], 'beginner', ARRAY['none'], 3, 15, NULL, ARRAY['strengthening', 'postural', 'scapular stability'], true),

('Rows with Resistance Band', 'Horizontal pulling for scapular retractors and posterior deltoid', 'Patient standing facing a door anchor or fixed point with the resistance band at chest height. Arms extended forward, grasp the band. Pull the elbows back, squeezing the scapulae together at end range. Hold 2 seconds. Slowly return with eccentric control. Maintain upright posture and avoid compensatory lumbar extension. Elbows should track close to the body. This exercise targets the middle trapezius, rhomboids, and posterior deltoid.', ARRAY['shoulder', 'scapula'], 'intermediate', ARRAY['resistance band'], 3, 12, NULL, ARRAY['strengthening', 'scapular stability', 'pulling'], true),

('Shoulder Abduction to 90 Degrees (Scapular Plane)', 'Deltoid and supraspinatus strengthening in the scapular plane', 'Patient standing with the arm at the side, thumb up. Raise the arm in the scapular plane (approximately 30-45 degrees anterior to the frontal plane) to 90 degrees. Hold 2 seconds. Lower with control. Avoid going above 90 degrees if there is impingement pathology. Thumb-up position reduces subacromial compression. Progress by adding light dumbbells (1-5 lbs). Monitor for compensatory scapular hiking.', ARRAY['shoulder'], 'intermediate', ARRAY['none', 'light dumbbells'], 3, 12, NULL, ARRAY['strengthening', 'deltoid', 'supraspinatus'], true),

('Sleeper Stretch (Posterior Capsule)', 'Stretch for posterior shoulder capsule tightness and glenohumeral internal rotation deficit (GIRD)', 'Patient sidelying on the involved side with shoulder and elbow both flexed to 90 degrees. Using the uninvolved hand, gently push the involved forearm toward the table/floor, internally rotating the shoulder. Apply gentle sustained pressure. Hold 30 seconds. The patient should feel a stretch in the posterior shoulder. Do not force through pain. Contraindicated post-surgical if internal rotation is restricted by protocol. Commonly used in overhead athletes with GIRD.', ARRAY['shoulder'], 'intermediate', ARRAY['none'], 3, 1, 30, ARRAY['stretching', 'posterior capsule', 'GIRD', 'sports rehab'], true),

('Cross-Body Adduction Stretch (Posterior Deltoid/Capsule)', 'Horizontal adduction stretch for posterior shoulder structures', 'Patient standing or seated. Bring the involved arm across the body at shoulder height. Use the uninvolved hand to gently pull the arm further across the chest at the distal humerus (not the elbow joint). Hold 30 seconds. The patient should feel a stretch in the posterior shoulder. Avoid compressing the AC joint — if anterior shoulder pain occurs, lower the arm slightly. Alternative to the sleeper stretch for posterior capsule tightness.', ARRAY['shoulder'], 'beginner', ARRAY['none'], 3, 1, 30, ARRAY['stretching', 'flexibility', 'posterior capsule'], true),

('Shoulder ER at 90/90 with Resistance Band', 'External rotation strengthening in the 90-degree abducted position for overhead athletes', 'Patient standing with the shoulder abducted to 90 degrees, elbow flexed to 90 degrees. Anchor the resistance band at elbow height. Starting with the forearm parallel to the floor, rotate the forearm upward toward the ceiling against the resistance. Slowly return. Maintain the upper arm position throughout. This exercise mimics the late cocking phase of throwing and targets the rotator cuff in a sport-specific position. Not appropriate in early post-surgical phases.', ARRAY['shoulder', 'rotator cuff'], 'advanced', ARRAY['resistance band'], 3, 10, NULL, ARRAY['strengthening', 'rotator cuff', 'sports rehab', 'overhead athlete'], true),

('Push-Up Plus (Serratus Anterior)', 'Closed chain scapular protraction for serratus anterior strengthening', 'Begin in a push-up position (or modified on knees). Perform a standard push-up. At the top of the movement, continue pressing upward by protracting the scapulae (pushing the upper back toward the ceiling). This "plus" phase is the key movement. Slowly retract and lower into the next rep. The serratus anterior is the primary scapular protractor and upward rotator. Essential for scapular dyskinesis rehabilitation. Modify to a wall push-up plus for lower-level patients.', ARRAY['shoulder', 'scapula', 'core'], 'intermediate', ARRAY['none'], 3, 10, NULL, ARRAY['strengthening', 'scapular stability', 'serratus anterior', 'closed chain'], true),

-- ============================================================
-- ELBOW / WRIST / HAND (Exercises 43-50)
-- ============================================================

('Wrist Flexor Stretch', 'Sustained stretch of the wrist flexor-pronator mass for medial epicondylalgia management', 'Patient extends the involved arm forward with the elbow fully extended and the palm facing up (supinated). Using the opposite hand, gently extend the wrist and fingers by pulling them back toward the body. Hold 30 seconds. The patient should feel a stretch along the medial forearm. Keep the elbow straight throughout. Perform before and after aggravating activities. Commonly prescribed for medial epicondylitis (golfer''s elbow) and carpal tunnel syndrome.', ARRAY['wrist', 'hand', 'elbow'], 'beginner', ARRAY['none'], 3, 1, 30, ARRAY['stretching', 'flexibility', 'epicondylitis'], true),

('Wrist Extensor Stretch', 'Sustained stretch of the wrist extensor mass for lateral epicondylalgia management', 'Patient extends the involved arm forward with the elbow fully extended and the palm facing down (pronated). Using the opposite hand, gently flex the wrist by pushing the hand downward and slightly inward. Hold 30 seconds. The patient should feel a stretch along the lateral forearm/extensor mass. Keep the elbow straight. Commonly prescribed for lateral epicondylitis (tennis elbow).', ARRAY['wrist', 'hand', 'elbow'], 'beginner', ARRAY['none'], 3, 1, 30, ARRAY['stretching', 'flexibility', 'epicondylitis', 'tennis elbow'], true),

('Eccentric Wrist Extension (Tyler Twist Alternative)', 'Eccentric loading of the wrist extensors for lateral epicondylitis', 'Patient seated with the forearm supported on a table, wrist over the edge, palm facing down. Hold a light dumbbell (1-3 lbs). Start with the wrist extended. Slowly lower the weight by flexing the wrist through a count of 5 seconds (eccentric phase). Use the uninvolved hand to assist returning to the extended start position. The therapeutic component is the slow lowering phase only. Eccentric loading has strong evidence for tendinopathy rehabilitation.', ARRAY['wrist', 'elbow'], 'intermediate', ARRAY['light dumbbells'], 3, 12, NULL, ARRAY['strengthening', 'eccentric', 'tendinopathy', 'tennis elbow'], true),

('Wrist Curls (Flexion/Extension)', 'Concentric forearm strengthening for wrist flexors and extensors', 'Patient seated with the forearm resting on the thigh or table, wrist over the edge. For flexion curls: palm facing up, curl the weight upward by flexing the wrist. For extension curls: palm facing down, raise the hand by extending the wrist. Perform each direction for the prescribed reps. Use a light dumbbell (1-5 lbs). Move through the full available ROM. Control the eccentric (lowering) phase for 3 seconds.', ARRAY['wrist', 'hand', 'elbow'], 'beginner', ARRAY['light dumbbells'], 3, 12, NULL, ARRAY['strengthening', 'forearm'], true),

('Grip Strengthening (Putty or Hand Gripper)', 'Intrinsic and extrinsic hand strengthening for grip weakness', 'Patient seated with the forearm supported. Using therapy putty or a hand gripper, perform sustained grip squeezes. Hold each squeeze for 5 seconds. Relax fully between reps. With putty, vary the exercises: full grip squeeze, finger extension against putty, pinch grip, and finger abduction/adduction. Match putty resistance to patient tolerance (tan = XX-soft through black = X-firm). Monitor for exacerbation of carpal tunnel or trigger finger symptoms.', ARRAY['hand', 'wrist'], 'beginner', ARRAY['therapy putty', 'hand gripper'], 3, 15, NULL, ARRAY['strengthening', 'grip', 'hand therapy'], true),

('Tendon Gliding Exercises', 'Sequential finger positions to maximize differential tendon excursion', 'Patient performs five positions in sequence: (1) Straight — all fingers and thumb extended; (2) Hook — DIP and PIP flexed, MCP extended; (3) Full fist — all joints fully flexed; (4) Tabletop — MCP flexed, PIP/DIP extended; (5) Straight fist — MCP and PIP flexed, DIP extended. Hold each position 3-5 seconds. This sequence produces maximum differential gliding of the FDP and FDS tendons. Essential post flexor tendon repair, trigger finger release, and carpal tunnel release.', ARRAY['hand', 'wrist'], 'beginner', ARRAY['none'], 3, 10, NULL, ARRAY['mobility', 'tendon gliding', 'hand therapy', 'post-surgical'], true),

('Nerve Gliding / Median Nerve Flossing', 'Neural mobilization for the median nerve to address carpal tunnel syndrome', 'Patient seated with upright posture. Begin with the shoulder depressed, elbow flexed, wrist in neutral, and fingers in a fist. Sequentially: (1) extend the fingers and wrist; (2) extend the elbow; (3) supinate the forearm; (4) extend the wrist further; (5) laterally flex the neck away from the involved side. Move slowly through each stage. If paresthesias increase, do not advance further. This is a tensioner technique; to convert to a slider, flex the neck toward the involved side at the end. Use clinical judgment to select tensioner vs. slider based on irritability.', ARRAY['hand', 'wrist', 'elbow'], 'intermediate', ARRAY['none'], 3, 10, NULL, ARRAY['mobility', 'neural mobilization', 'carpal tunnel', 'nerve gliding'], true),

('Pronation/Supination with Hammer', 'Forearm rotation strengthening using a weighted lever arm', 'Patient seated with the elbow flexed to 90 degrees, forearm supported on the thigh or table edge. Grasp a hammer or weighted bar at the handle (farther from the weight = more resistance). Slowly rotate the forearm into pronation (palm down), then supination (palm up). Control the motion throughout the full range. Move through a count of 3 seconds in each direction. Progress by gripping the handle farther from the weight. Useful for distal radius fracture rehab and forearm strengthening.', ARRAY['elbow', 'wrist'], 'intermediate', ARRAY['hammer', 'weighted bar'], 3, 12, NULL, ARRAY['strengthening', 'forearm', 'rotation'], true),

-- ============================================================
-- HIP (Exercises 51-62)
-- ============================================================

('Hip Bridges (Glute Bridge)', 'Supine hip extension strengthening for glutes and posterior chain', 'Patient supine with knees bent to approximately 45 degrees, feet flat and hip-width apart. Squeeze the gluteals and lift the hips toward the ceiling until the body forms a straight line from shoulders to knees. Hold 3-5 seconds at the top. Lower slowly with control. Avoid hyperextending the lumbar spine at the top — the motion should come from the hips. Cue: "Squeeze your glutes to lift, not your back." Progress to single-leg bridges or add a resistance band above the knees.', ARRAY['hip', 'glutes', 'core'], 'beginner', ARRAY['none'], 3, 12, NULL, ARRAY['strengthening', 'glutes', 'posterior chain'], true),

('Clamshells', 'Hip external rotator and gluteus medius strengthening in sidelying', 'Patient sidelying with hips flexed to approximately 45 degrees and knees bent. Feet remain together. Keeping the pelvis stable (do not roll backward), raise the top knee as high as possible by externally rotating the hip. Hold 2-3 seconds. Lower with control. The motion should come from the hip, not the pelvis. If the pelvis rolls back, the range is too large. Progress by adding a resistance band just above the knees. A foundational exercise for hip abductor and external rotator deficits.', ARRAY['hip', 'glutes'], 'beginner', ARRAY['none', 'resistance band'], 3, 15, NULL, ARRAY['strengthening', 'hip stability', 'gluteus medius'], true),

('Monster Walks (Lateral Band Walks)', 'Dynamic gluteus medius and hip abductor strengthening', 'Place a resistance band around the ankles (or just above the knees for less resistance). Stand in a mini-squat position (quarter squat) with feet hip-width apart. Maintain the squat depth while stepping laterally, keeping tension on the band throughout. Take 10-15 steps in one direction, then return. Keep the toes pointed forward (avoid turning the feet out). Maintain an upright trunk. Cue: "Stay low and push out against the band with each step."', ARRAY['hip', 'glutes'], 'intermediate', ARRAY['resistance band'], 3, 15, NULL, ARRAY['strengthening', 'hip stability', 'gluteus medius', 'functional'], true),

('Standing Hip Abduction', 'Open-chain hip abductor strengthening against gravity', 'Patient standing holding a stable surface for balance. Lift the involved leg out to the side, keeping the toe pointed forward and the trunk upright. Raise to approximately 30-45 degrees. Hold 2 seconds. Lower with control. Do not lean the trunk over the stance leg. The pelvis should remain level. Progress by adding an ankle weight or cuff weight. Targets the gluteus medius, gluteus minimus, and TFL.', ARRAY['hip', 'glutes'], 'beginner', ARRAY['none', 'ankle weight'], 3, 12, NULL, ARRAY['strengthening', 'hip abductor'], true),

('Hip Flexor Stretch (Half-Kneeling)', 'Sustained stretch of the iliopsoas and rectus femoris', 'Patient in half-kneeling position (involved knee on the floor, uninvolved foot forward). Ensure the trunk is upright. Posteriorly tilt the pelvis (tuck the tailbone under). Shift the body weight forward over the front foot until a stretch is felt in the anterior hip of the kneeling leg. Hold 30 seconds. For rectus femoris bias, grasp the back foot and pull the heel toward the buttock. Do not hyperextend the lumbar spine. Place a pad under the knee for comfort.', ARRAY['hip'], 'beginner', ARRAY['none', 'pad'], 3, 1, 30, ARRAY['stretching', 'flexibility', 'hip flexor', 'iliopsoas'], true),

('Piriformis Stretch (Figure-4)', 'Stretches the piriformis and deep hip external rotators', 'Patient supine. Cross the involved ankle over the opposite knee (figure-4 position). Grasp behind the thigh of the uncrossed leg and pull it toward the chest. The patient should feel a deep stretch in the posterior/lateral buttock of the crossed leg. Hold 30 seconds. Avoid pulling on the tibial tuberosity. If unable to reach behind the thigh, use a towel or strap. Commonly prescribed for piriformis syndrome and sciatic nerve irritation.', ARRAY['hip', 'glutes'], 'beginner', ARRAY['none'], 3, 1, 30, ARRAY['stretching', 'flexibility', 'piriformis', 'sciatic'], true),

('Single-Leg Romanian Deadlift (RDL)', 'Hip hinge pattern for posterior chain strengthening and balance', 'Patient standing on the involved leg with a slight knee bend. Hinge at the hip, lowering the trunk forward while extending the uninvolved leg behind. Reach toward the floor with the hands or a dumbbell. The back should remain flat throughout. Return to upright by squeezing the glute. The stance knee stays slightly bent and does not change angle. The motion is purely at the hip. Progress by adding a dumbbell. This challenges hip stability, hamstring length, and proprioception simultaneously.', ARRAY['hip', 'hamstrings', 'glutes'], 'advanced', ARRAY['none', 'dumbbell'], 3, 10, NULL, ARRAY['strengthening', 'balance', 'functional', 'posterior chain'], true),

('Standing Hip Flexion (Marching)', 'Hip flexor strengthening and single-leg stance stability', 'Patient standing holding a stable surface if needed. Lift the involved knee toward the chest to approximately 90 degrees of hip flexion. Hold 2-3 seconds. Lower with control. Maintain upright posture and a level pelvis throughout. The stance leg should remain stable with the knee slightly bent. Progress by removing hand support, adding an ankle weight, or performing continuously (marching pattern). Useful for gait training and hip flexor strengthening post-THA.', ARRAY['hip', 'core'], 'beginner', ARRAY['none', 'ankle weight'], 3, 12, NULL, ARRAY['strengthening', 'hip flexor', 'gait training', 'balance'], true),

('Quadruped Hip Extension (Donkey Kicks)', 'Gluteus maximus isolation in a gravity-eliminated position', 'Patient in quadruped with neutral spine. Keeping the knee bent to 90 degrees, lift the involved leg by extending the hip, pressing the sole of the foot toward the ceiling. Raise until the thigh is parallel to the floor. Do not hyperextend the lumbar spine or rotate the pelvis. Hold 2-3 seconds. Lower with control. The motion should occur at the hip only. Cue: "Push the ceiling away with the bottom of your foot." Progress with ankle weight.', ARRAY['hip', 'glutes'], 'beginner', ARRAY['none', 'ankle weight'], 3, 12, NULL, ARRAY['strengthening', 'glutes', 'isolation'], true),

('Supine Hip ER/IR AROM', 'Active hip rotation range of motion in a gravity-eliminated position', 'Patient supine with the involved hip and knee flexed to 90 degrees. Keeping the thigh vertical, slowly rotate the shin inward (hip external rotation) and outward (hip internal rotation) through the full available range. Move rhythmically. 1 rep = full arc of rotation (ER + IR). Avoid pelvic motion. This is useful for assessing and maintaining hip rotational ROM post-THA or in FAI management. Note: hip ER = shin moves inward in this position.', ARRAY['hip'], 'beginner', ARRAY['none'], 3, 10, NULL, ARRAY['mobility', 'range of motion', 'hip rotation'], true),

('Seated Hip Adduction with Ball Squeeze', 'Isometric hip adductor strengthening', 'Patient seated with upright posture. Place a ball (6-8 inch diameter) or folded pillow between the knees. Squeeze the knees together against the ball. Hold 5 seconds. Relax. This isometric exercise targets the adductor magnus, longus, and brevis. Commonly used early post-THA, post-TKA, or for groin strain rehabilitation. Progress by increasing hold duration or using a firmer object.', ARRAY['hip'], 'beginner', ARRAY['ball', 'pillow'], 3, 15, NULL, ARRAY['strengthening', 'isometric', 'hip adductor', 'post-surgical'], true),

('Fire Hydrants (Quadruped Hip Abduction)', 'Hip abduction in a quadruped position targeting the gluteus medius', 'Patient in quadruped with neutral spine. Keeping the knee bent to 90 degrees, lift the involved leg out to the side (hip abduction) while maintaining a stable pelvis and trunk. Raise to approximately 45 degrees or until the pelvis begins to shift. Hold 2-3 seconds. Lower with control. Do not rotate the trunk. This exercise challenges the gluteus medius in a different plane than sidelying abduction. Progress with resistance band around the thighs.', ARRAY['hip', 'glutes'], 'intermediate', ARRAY['none', 'resistance band'], 3, 12, NULL, ARRAY['strengthening', 'gluteus medius', 'hip stability'], true),

-- ============================================================
-- KNEE (Exercises 63-72)
-- ============================================================

('Quad Sets (Isometric Quadriceps Activation)', 'Isometric quadriceps contraction for early knee rehabilitation', 'Patient seated or supine with the involved leg extended. Instruct the patient to contract the quadriceps by pushing the posterior knee into the surface. The patella should glide superiorly with a proper contraction. Hold 5-10 seconds. Relax completely. Cue: "Tighten your thigh muscle and try to push the back of your knee flat into the table." A rolled towel under the knee can provide a target for the contraction. This is the first-line exercise post-TKA, ACL reconstruction, and meniscectomy.', ARRAY['knee', 'quadriceps'], 'beginner', ARRAY['none'], 3, 15, NULL, ARRAY['strengthening', 'isometric', 'post-surgical', 'quad activation'], true),

('Straight Leg Raises (SLR)', 'Quadriceps strengthening without knee joint motion', 'Patient supine with the uninvolved knee bent and foot flat. Lock the involved knee in full extension by performing a quad set. Maintaining the quad contraction, lift the straight leg to approximately 45 degrees (match the angle of the opposite thigh). Hold 3 seconds. Lower slowly. If an extensor lag is present (inability to fully extend the knee), do not perform until full active extension is achieved. Progress with ankle weights (1-5 lbs). 4-way SLRs: repeat in sidelying (abduction/adduction) and prone (extension).', ARRAY['knee', 'quadriceps', 'hip'], 'beginner', ARRAY['none', 'ankle weight'], 3, 12, NULL, ARRAY['strengthening', 'post-surgical'], true),

('Terminal Knee Extension (Short Arc Quad)', 'Quadriceps strengthening through the final 30 degrees of extension', 'Patient supine or seated with a bolster/rolled towel placed under the involved knee, supporting it in approximately 30 degrees of flexion. Extend the knee fully against gravity (or with a resistance band around the ankle). Hold 3-5 seconds at full extension. Lower slowly. This isolates the VMO and quadriceps through the terminal range, which is the most difficult range to achieve post-surgically. Essential after ACL reconstruction and TKA.', ARRAY['knee', 'quadriceps'], 'beginner', ARRAY['bolster', 'resistance band'], 3, 15, NULL, ARRAY['strengthening', 'VMO', 'terminal extension'], true),

('Wall Squats (Wall Sits)', 'Closed-chain quadriceps and gluteal co-contraction strengthening', 'Patient standing with back against a wall, feet shoulder-width apart and 18-24 inches from the wall. Slide down the wall by bending the knees until the thighs approach parallel to the floor (or as tolerated). Knees should not extend past the toes. Hold for the prescribed duration (isometric) or slide up and down for reps (isotonic). Keep the weight through the heels. This is a safe closed-chain alternative to open-chain knee extension when ACL precautions apply.', ARRAY['knee', 'quadriceps', 'glutes'], 'intermediate', ARRAY['none'], 3, 10, NULL, ARRAY['strengthening', 'functional', 'closed chain'], true),

('Step-Ups', 'Functional closed-chain knee/hip strengthening mimicking stair ascent', 'Patient standing in front of a step (start with 4-6 inch, progress to 8 inch). Step up with the involved leg, fully extending the knee and hip at the top. Bring the uninvolved foot to the step briefly, then lower the uninvolved leg slowly back to the floor by bending the involved knee. The involved leg controls the descent. Maintain trunk upright and knee tracking over the 2nd toe. Watch for valgus collapse. Progress by increasing step height or adding hand-held weights.', ARRAY['knee', 'quadriceps', 'glutes', 'hip'], 'intermediate', ARRAY['step platform'], 3, 10, NULL, ARRAY['strengthening', 'functional', 'closed chain', 'stair training'], true),

('Hamstring Curls (Standing)', 'Open-chain hamstring strengthening', 'Patient standing holding a stable surface. Bend the involved knee, bringing the heel toward the buttock. Hold 2 seconds at end range. Lower slowly with a 3-second eccentric phase. Keep the thighs parallel — avoid hip flexion or extension during the movement. Progress by adding ankle weight or cuff weight (1-5 lbs). Targets the biceps femoris, semimembranosus, and semitendinosus. Important for hamstring:quadriceps strength ratio balance and ACL injury prevention.', ARRAY['knee', 'hamstrings'], 'beginner', ARRAY['none', 'ankle weight'], 3, 12, NULL, ARRAY['strengthening', 'hamstring'], true),

('Hamstring Stretch (Supine with Strap)', 'Sustained hamstring stretch in a controlled supine position', 'Patient supine with the uninvolved leg flat or knee bent. Loop a strap or belt around the arch of the involved foot. Keeping the knee extended, use the strap to raise the leg toward the ceiling until a stretch is felt in the posterior thigh. Hold 30 seconds. Keep the knee as straight as possible. The pelvis should remain flat on the surface. Avoid pulling into discomfort above a 3/10. The contralateral leg should remain on the surface to stabilize the pelvis.', ARRAY['knee', 'hamstrings'], 'beginner', ARRAY['strap', 'belt'], 3, 1, 30, ARRAY['stretching', 'flexibility', 'hamstring'], true),

('Seated Knee Extension (Open Chain)', 'Quadriceps strengthening through full or partial arc of knee extension', 'Patient seated on the edge of a table or in a chair. Extend the involved knee to full extension. Hold 3 seconds. Lower slowly. May use an ankle weight or resistance band for progressive loading. For patellofemoral pathology, limit the arc to the terminal 30 degrees (90-60 degrees of flexion is avoided as it creates maximal patellofemoral joint reaction force). For general quad strengthening, use full arc. Monitor for crepitus and anterior knee pain.', ARRAY['knee', 'quadriceps'], 'beginner', ARRAY['none', 'ankle weight'], 3, 12, NULL, ARRAY['strengthening', 'open chain'], true),

('Lateral Step-Downs', 'Eccentric quadriceps control and patellar tracking assessment/training', 'Patient standing on a 4-6 inch step with the involved leg at the edge. Slowly lower the uninvolved leg toward the floor by bending the involved knee. Lightly touch the heel to the floor, then return to full extension. The involved leg does all the work. Watch for knee valgus, lateral trunk lean, and poor patellar tracking. This is both a clinical assessment tool and an exercise. Progress by increasing step height. Highly functional for stair descent training.', ARRAY['knee', 'quadriceps', 'hip', 'glutes'], 'intermediate', ARRAY['step platform'], 3, 10, NULL, ARRAY['strengthening', 'eccentric', 'functional', 'patellar tracking'], true),

('Patellar Mobilization (Self)', 'Patient self-mobilization of the patella to address patellofemoral restrictions', 'Patient seated with the involved knee extended and the quadriceps relaxed. Using the thumb and index finger, gently glide the patella superiorly, inferiorly, medially, and laterally. Hold each glide for 10 seconds. Perform 5-10 repetitions in each direction. Focus on the direction of restriction (typically inferior and medial glides are restricted post-surgically). Do not force through bony end-feels. Commonly prescribed post-TKA to restore patellar mobility for knee flexion.', ARRAY['knee'], 'beginner', ARRAY['none'], 3, 10, NULL, ARRAY['mobility', 'mobilization', 'patellofemoral', 'post-surgical'], true),

-- ============================================================
-- ANKLE / FOOT (Exercises 73-80)
-- ============================================================

('Ankle Pumps', 'Active ankle dorsiflexion/plantarflexion for circulation and mobility', 'Patient supine or seated with the leg elevated. Actively dorsiflex (pull toes toward shin) and plantarflex (point toes away) through the full available range. Move rhythmically at approximately 1 cycle per second. Perform 20-30 reps per set. This promotes venous return, reduces edema, and maintains ankle ROM. Indicated immediately post-operatively (TKA, THA, ankle surgery), during bed rest, and for DVT prophylaxis. Add ankle circles for circumduction mobility.', ARRAY['ankle', 'foot'], 'beginner', ARRAY['none'], 3, 20, NULL, ARRAY['mobility', 'circulation', 'post-surgical'], true),

('Heel Raises (Calf Raises)', 'Gastrocnemius and soleus strengthening for ankle plantarflexion power', 'Patient standing at the edge of a step holding a railing for balance. Rise up onto the balls of the feet as high as possible, contracting the calf muscles. Hold 2 seconds at the top. Lower the heels slowly below the step level for a full eccentric stretch through the calf. Control the lowering phase for 3-4 seconds. For Achilles tendinopathy, perform the eccentric (lowering) phase only, using the uninvolved leg to return to the top. Progress to single-leg. Alfredson protocol: 3x15 with knee straight (gastroc bias) and 3x15 with knee bent (soleus bias).', ARRAY['ankle', 'calf'], 'intermediate', ARRAY['step platform'], 3, 15, NULL, ARRAY['strengthening', 'eccentric', 'Achilles tendinopathy', 'calf'], true),

('Towel Scrunches (Intrinsic Foot Strengthening)', 'Strengthening of the intrinsic foot muscles for arch support', 'Patient seated with the involved foot on a towel placed on a smooth floor surface. Using only the toes, scrunch the towel toward the body by flexing the toes. Spread the toes and repeat. Complete the full length of the towel. Reset and repeat for prescribed sets. Alternatively, place small marbles or objects on the floor and pick them up with the toes. Targets the lumbricals, interossei, and flexor digitorum brevis. Important for plantar fasciitis, flat foot, and post-metatarsal fracture rehabilitation.', ARRAY['foot'], 'beginner', ARRAY['towel'], 3, 15, NULL, ARRAY['strengthening', 'intrinsic foot', 'arch support', 'plantar fasciitis'], true),

('Ankle Alphabet', 'Multi-directional active ankle range of motion exercise', 'Patient seated or supine with the foot unsupported. Using the big toe as a pointer, trace the letters of the alphabet in the air by moving the ankle through all planes of motion. Move slowly and deliberately through each letter, emphasizing the full range of dorsiflexion, plantarflexion, inversion, and eversion. Complete A through Z as one set. This addresses mobility in all planes simultaneously and is more engaging than isolated ROM exercises. Commonly used post ankle sprain or fracture.', ARRAY['ankle', 'foot'], 'beginner', ARRAY['none'], 3, 1, NULL, ARRAY['mobility', 'range of motion', 'ankle sprain'], true),

('Resisted Ankle Eversion with Band', 'Peroneal strengthening for lateral ankle stability', 'Patient seated with legs extended and the resistance band looped around the forefoot, anchored to a fixed point medially (or around the other foot). Evert the foot (turn the sole outward) against the band resistance. Slowly return with eccentric control. Keep the knee still — the motion should come from the ankle only. This targets the peroneus longus and brevis, which are critical for lateral ankle stability and prevention of recurrent inversion sprains. 3-second eccentric phase.', ARRAY['ankle', 'foot'], 'intermediate', ARRAY['resistance band'], 3, 15, NULL, ARRAY['strengthening', 'ankle stability', 'peroneal', 'inversion sprain prevention'], true),

('Resisted Ankle Inversion with Band', 'Posterior tibialis and ankle invertor strengthening', 'Patient seated with legs extended and the resistance band looped around the forefoot, anchored laterally. Invert the foot (turn the sole inward) against the band resistance. Slowly return with eccentric control. Keep the knee still. Targets the tibialis posterior, which is the primary dynamic stabilizer of the medial longitudinal arch. Important for posterior tibial tendon dysfunction (PTTD), flat foot correction, and medial ankle stability.', ARRAY['ankle', 'foot'], 'intermediate', ARRAY['resistance band'], 3, 15, NULL, ARRAY['strengthening', 'ankle stability', 'tibialis posterior'], true),

('Standing Calf Stretch (Gastrocnemius)', 'Sustained stretch of the gastrocnemius muscle in weight-bearing', 'Patient standing facing a wall with hands on the wall at chest height. Step the involved leg back into a lunge position. Keep the back knee straight and the heel on the floor. Lean forward by bending the front knee until a stretch is felt in the posterior calf of the back leg. Hold 30 seconds. The foot should be pointed straight ahead, not externally rotated. For soleus bias, repeat with the back knee slightly bent. Both stretches should be performed for comprehensive calf flexibility.', ARRAY['ankle', 'calf'], 'beginner', ARRAY['none'], 3, 1, 30, ARRAY['stretching', 'flexibility', 'calf', 'gastrocnemius'], true),

('Single-Leg Stance on Foam or BOSU', 'Advanced proprioceptive and balance training for ankle instability', 'Patient standing on the involved leg on an unstable surface (foam pad, BOSU ball, or wobble board). Maintain balance for the prescribed duration. Arms may be at the sides, on the hips, or crossed over the chest (progressively more challenging). Progress by closing the eyes, turning the head, catching/throwing a ball, or performing cognitive dual-tasking. Essential for chronic ankle instability rehabilitation. Begin on a firm surface before progressing to unstable surfaces. Safety: have a stable support surface within reach.', ARRAY['ankle', 'foot', 'hip'], 'advanced', ARRAY['foam pad', 'BOSU ball'], 3, 1, 30, ARRAY['balance', 'proprioception', 'ankle stability', 'advanced'], true),

-- ============================================================
-- BALANCE AND FALL PREVENTION (Exercises 81-87)
-- ============================================================

('Single-Leg Balance (Firm Surface)', 'Static single-limb balance for proprioception and fall risk reduction', 'Patient standing on one leg near a counter or stable surface for safety. Maintain balance for the prescribed duration with eyes open. The stance knee should be slightly bent, not locked. Maintain a level pelvis. Arms at sides. If unable to hold for 10 seconds, this indicates fall risk. Progress: eyes closed, foam surface, perturbation training, and head turns. Track and document hold times for objective balance assessment. Normative: age 60-69 should hold 22+ seconds with eyes open.', ARRAY['ankle', 'hip', 'core'], 'beginner', ARRAY['none'], 3, 1, 30, ARRAY['balance', 'proprioception', 'fall prevention'], true),

('Tandem Stance (Heel-to-Toe Standing)', 'Narrow base of support balance challenge', 'Patient standing with one foot directly in front of the other, heel touching toe (tandem position). Arms at sides. Maintain balance for the prescribed duration. The test position is with the dominant foot behind. Progress by closing the eyes or placing hands on hips. If unable to hold for 10 seconds, this indicates increased fall risk. Place near a counter for safety. This challenges medial-lateral stability and is a component of the Romberg and BESS tests.', ARRAY['ankle', 'hip', 'core'], 'intermediate', ARRAY['none'], 3, 1, 30, ARRAY['balance', 'fall prevention', 'proprioception'], true),

('Tandem Walking (Heel-to-Toe Walking)', 'Dynamic balance challenge with narrow base of support during gait', 'Patient walks in a straight line placing the heel of one foot directly in front of the toes of the other foot. Arms may be at sides or extended for balance. Take 10-20 steps. Maintain upright posture and a forward gaze (not looking at the feet). This challenges the vestibular and proprioceptive systems and is a standard clinical balance assessment. Progress by turning the head side-to-side during walking, walking backward, or walking on a foam surface.', ARRAY['ankle', 'hip', 'core'], 'intermediate', ARRAY['none'], 3, 20, NULL, ARRAY['balance', 'fall prevention', 'gait training', 'vestibular'], true),

('Sit-to-Stand (Chair Rises)', 'Functional lower extremity strengthening and fall prevention exercise', 'Patient seated in a standard-height chair (approximately 17 inches) with feet flat on the floor, shoulder-width apart. Cross the arms over the chest (to prevent upper extremity compensation). Stand up fully without using the arms. Sit back down slowly with control (4-second descent). The 5x Sit-to-Stand test time is a validated fall risk measure (>12 seconds = increased risk). For exercise purposes, perform 10 reps with controlled descent. Progress by lowering the chair height or holding a weight.', ARRAY['knee', 'hip', 'quadriceps', 'glutes'], 'beginner', ARRAY['chair'], 3, 10, NULL, ARRAY['functional', 'strengthening', 'fall prevention', 'outcome measure'], true),

('Multi-Directional Reaching (Star Excursion Pattern)', 'Dynamic balance reaching in multiple directions', 'Patient standing on the involved leg with hands on hips. Reach the uninvolved leg as far as possible in 8 directions (anterior, anterolateral, lateral, posterolateral, posterior, posteromedial, medial, anteromedial) while maintaining single-leg balance. Lightly touch the floor with the foot and return to the starting position. The stance knee should bend to accommodate the reach. This is based on the Star Excursion Balance Test / Y-Balance Test and has normative data for return-to-sport criteria.', ARRAY['ankle', 'hip', 'knee', 'core'], 'advanced', ARRAY['none'], 3, 8, NULL, ARRAY['balance', 'proprioception', 'sports rehab', 'dynamic stability'], true),

('Backward Walking (Retro Walking)', 'Dynamic balance and quadriceps strengthening through backward gait', 'Patient walks backward in a straight line in a clear, safe environment. Start slowly with short steps. Emphasize toe-to-heel foot contact pattern (reverse of normal gait). Maintain upright posture. Progress distance and speed as confidence improves. Retro walking reduces patellofemoral joint stress while strengthening the quadriceps eccentrically. It also challenges the proprioceptive and vestibular systems. Ensure the path is clear of obstacles. Useful for patellofemoral pain, TKA rehab, and gait retraining.', ARRAY['knee', 'hip', 'ankle'], 'intermediate', ARRAY['none'], 3, 1, 60, ARRAY['gait training', 'balance', 'functional', 'patellofemoral'], true),

('Lateral Stepping Over Obstacles', 'Dynamic lateral balance and hip abductor control during stepping', 'Set up 3-5 small obstacles (cones, cups, or small hurdles, 4-6 inches high) in a line. Patient side-steps over each obstacle, lifting the leg laterally to clear the obstacle. Maintain upright posture and do not rotate the trunk. Step over in one direction, then return. This challenges hip abductor strength, lateral weight shifting, and dynamic balance simultaneously. Progress by increasing obstacle height or speed. Important for fall prevention in the community-dwelling elderly.', ARRAY['hip', 'ankle', 'core'], 'intermediate', ARRAY['cones', 'small hurdles'], 3, 10, NULL, ARRAY['balance', 'fall prevention', 'functional', 'obstacle negotiation'], true),

-- ============================================================
-- NEUROLOGICAL REHABILITATION (Exercises 88-93)
-- ============================================================

('Weight Shifting (Standing)', 'Postural control and weight transfer training for neurological populations', 'Patient standing with feet shoulder-width apart, holding a stable surface if needed. Slowly shift weight toward the right foot, then to the left foot, then forward over the toes, then backward over the heels. Hold each position for 5-10 seconds. The goal is to expand the base of support boundaries. Visual targets may be used. Cue: "Sway like a tree in the wind — slowly and with control." This is foundational for patients post-stroke, with Parkinson disease, or with vestibular dysfunction.', ARRAY['ankle', 'hip', 'core'], 'beginner', ARRAY['none'], 3, 10, NULL, ARRAY['balance', 'neurological', 'weight shifting', 'postural control'], true),

('Seated Trunk Rotation with Reach', 'Trunk mobility and motor control for seated function in neurological patients', 'Patient seated with feet flat on the floor. Reach the involved arm across the body toward the opposite hip, rotating the trunk. Return to midline. Reach toward a target placed at varying heights and positions around the patient. This promotes trunk rotation, weight shifting in sitting, and reaching patterns needed for ADLs. For hemiplegic patients, the uninvolved arm may assist or guide the involved arm. Progress by increasing reach distance and varying target locations.', ARRAY['core', 'thoracic spine', 'shoulder'], 'beginner', ARRAY['none'], 3, 10, NULL, ARRAY['neurological', 'motor control', 'trunk mobility', 'ADL training'], true),

('Supine-to-Sit Transitions (Bed Mobility)', 'Functional bed mobility training for neurological populations', 'Patient supine in bed. Instruct the patient to roll onto one side (log roll or segmental roll as appropriate). Then, simultaneously lower the legs off the edge of the bed while pushing up with the arms to arrive in a seated position. Reverse the sequence to return to supine. Practice on both sides if possible. For hemiplegic patients, rolling toward the involved side may be easier; practice both directions. Break the movement into components and progress as motor control improves.', ARRAY['core', 'shoulder', 'hip'], 'beginner', ARRAY['bed', 'mat'], 3, 5, NULL, ARRAY['neurological', 'functional', 'bed mobility', 'ADL training'], true),

('Seated Marching (Hip Flexion)', 'Active hip flexion in seated position for neurological motor recovery', 'Patient seated with upright posture, feet flat on the floor. Lift one knee toward the chest (hip flexion) as high as possible. Hold 2-3 seconds. Lower slowly. Alternate legs in a marching pattern. For patients with hemiplegia, focus on the involved side and assist as needed. This exercise addresses hip flexor activation, trunk stability in sitting, and the reciprocal pattern needed for gait. Progress to standing marching when safe. Monitor for posterior trunk lean.', ARRAY['hip', 'core'], 'beginner', ARRAY['none'], 3, 10, NULL, ARRAY['neurological', 'strengthening', 'motor control', 'gait preparation'], true),

('Heel-Toe Rocking (Seated or Standing)', 'Ankle dorsiflexion/plantarflexion motor control for gait preparation', 'Patient seated or standing (supported). Rock the feet from heels to toes and back in a rhythmic pattern. In seated: lift the toes (dorsiflexion), then lift the heels (plantarflexion). In standing: shift weight from heels to toes and back. Emphasize the dorsiflexion component, as foot drop is common post-stroke. Progress from seated to standing. Use a metronome for rhythmic cuing if appropriate (especially for Parkinson disease). This promotes the ankle strategy for postural control.', ARRAY['ankle', 'foot'], 'beginner', ARRAY['none'], 3, 15, NULL, ARRAY['neurological', 'motor control', 'gait preparation', 'ankle strategy'], true),

('Task-Specific Grasp and Release Practice', 'Functional hand motor recovery through repetitive task practice', 'Set up a variety of objects of different sizes and shapes (cups, cones, pegs, coins, buttons). Patient practices grasping each object and placing it in a designated location, then releasing. Vary the grasp pattern: cylindrical grasp (cup), spherical grasp (ball), lateral pinch (key), tip pinch (coin), and 3-jaw chuck (pen). Repetition and task-specificity drive neuroplastic motor recovery. Use objects relevant to the patient''s ADL goals. This can be combined with constraint-induced movement therapy principles for the involved hand.', ARRAY['hand', 'wrist'], 'intermediate', ARRAY['various objects', 'cones', 'pegs'], 3, 10, NULL, ARRAY['neurological', 'fine motor', 'hand therapy', 'ADL training', 'neuroplasticity'], true),

-- ============================================================
-- SPORTS REHABILITATION (Exercises 94-100)
-- ============================================================

('Lateral Lunges', 'Frontal plane hip and knee strengthening for lateral sport movements', 'Patient standing with feet together. Take a large step to the side with the involved leg, bending the knee and sitting the hips back into a lateral lunge. The uninvolved leg remains straight. Push off and return to the starting position. Keep the trunk upright and the lunging knee tracking over the 2nd toe. Depth should be to approximately 90 degrees of knee flexion or as tolerated. Progress by adding dumbbells or a resistance band. This mimics the lateral cutting and decelerating demands of sport.', ARRAY['hip', 'knee', 'glutes', 'quadriceps'], 'intermediate', ARRAY['none', 'dumbbell'], 3, 10, NULL, ARRAY['strengthening', 'sports rehab', 'functional', 'lateral movement'], true),

('Forward Lunges', 'Sagittal plane functional strengthening for deceleration and gait', 'Patient standing with feet hip-width apart. Step forward with the involved leg into a lunge position, lowering the back knee toward the floor. The front knee should bend to approximately 90 degrees and should not extend past the toes. Push off the front foot to return to standing. Maintain upright trunk posture throughout. Cue: "Drop straight down, then push back." Progress by adding dumbbells, increasing step length, or performing walking lunges. This trains eccentric quadriceps control and hip stability.', ARRAY['hip', 'knee', 'quadriceps', 'glutes'], 'intermediate', ARRAY['none', 'dumbbell'], 3, 10, NULL, ARRAY['strengthening', 'sports rehab', 'functional'], true),

('Box Jumps (or Step-Ups with Speed)', 'Plyometric lower extremity power development for sport return', 'Patient standing facing a plyo box or stable platform (start with 12-18 inch height). Perform a countermovement (quick squat) and explode upward, landing softly on top of the box with both feet. Step down (do not jump down initially). Focus on a soft, quiet landing with knees tracking over toes and hips absorbing the impact. This is a late-phase return-to-sport exercise. Prerequisites: pain-free single-leg squat, hop without pain, and adequate quadriceps strength (LSI >80%). Progress box height gradually.', ARRAY['knee', 'hip', 'ankle', 'quadriceps', 'glutes'], 'advanced', ARRAY['plyo box'], 3, 8, NULL, ARRAY['plyometric', 'sports rehab', 'power', 'return to sport'], true),

('Single-Leg Hop Test / Hop Training', 'Plyometric progression for return-to-sport testing and training', 'Patient standing on the involved leg. Hop forward as far as possible, landing on the same leg. Stick the landing for 2 seconds with good knee alignment (no valgus collapse). Measure the distance. Compare to the uninvolved side (Limb Symmetry Index target: >90%). This is both a return-to-sport criterion test (single hop for distance) and a training exercise. Progressions include triple hop, crossover hop, and 6-meter timed hop. Do not initiate until patient meets phase-appropriate criteria (typically 4-6 months post ACL reconstruction).', ARRAY['knee', 'hip', 'ankle'], 'advanced', ARRAY['none'], 3, 5, NULL, ARRAY['plyometric', 'sports rehab', 'return to sport', 'outcome measure', 'ACL'], true),

('Agility Ladder Drills', 'Multi-directional footwork and agility training for sport return', 'Place an agility ladder flat on the ground. Patient performs various foot patterns through the ladder: (1) Two feet in each box (forward); (2) Lateral shuffles; (3) In-in-out-out (Ickey shuffle); (4) Single-leg hops through each box. Start slowly for pattern acquisition, then increase speed. Focus on quick foot contacts, knee alignment, and upright posture. This develops coordination, reaction time, and neuromuscular control for sport-specific demands. Appropriate in the late return-to-sport phase.', ARRAY['ankle', 'knee', 'hip'], 'advanced', ARRAY['agility ladder'], 3, 5, NULL, ARRAY['agility', 'sports rehab', 'return to sport', 'coordination'], true),

('Nordic Hamstring Curl', 'Eccentric hamstring strengthening for hamstring strain prevention', 'Patient kneeling on a pad with the ankles secured (by a partner or under a fixed bar). Cross the arms over the chest. Slowly lower the body forward toward the ground by extending the knees while maintaining a rigid trunk (hip extended, not flexed). Control the descent as long as possible using eccentric hamstring contraction. When unable to hold, catch with the hands and push back to the starting position. This exercise has strong evidence (RCTs) for reducing hamstring strain injury rates by up to 51%. Begin with small-range controlled lowering and progress.', ARRAY['knee', 'hamstrings'], 'advanced', ARRAY['pad', 'partner or anchor'], 3, 5, NULL, ARRAY['strengthening', 'eccentric', 'sports rehab', 'injury prevention', 'hamstring'], true),

('Perturbation Training (Reactive Balance)', 'Unpredictable external perturbation for neuromuscular re-education', 'Patient standing on a wobble board, foam pad, or BOSU ball in single- or double-leg stance. The clinician or a partner provides unexpected perturbations (gentle pushes at the hips, shoulders, or trunk) in various directions. The patient reacts to maintain balance without stepping. Progress from predictable to unpredictable perturbations, double-leg to single-leg, eyes open to eyes closed, and firm to compliant surfaces. Perturbation training has Level I evidence for ACL injury reduction and is recommended in return-to-sport protocols.', ARRAY['knee', 'ankle', 'hip', 'core'], 'advanced', ARRAY['wobble board', 'foam pad', 'BOSU ball'], 3, 10, NULL, ARRAY['balance', 'proprioception', 'sports rehab', 'neuromuscular control', 'ACL prevention'], true),

('IT Band Foam Roll (Self-Myofascial Release)', 'Self-myofascial release of the iliotibial band and lateral thigh structures', 'Patient sidelying with the foam roller positioned under the lateral thigh between the hip and the knee. Support body weight with the forearms and the opposite foot placed in front for control. Slowly roll from just below the greater trochanter to just above the lateral femoral condyle over a 30-second period. Pause on tender points for 10-15 seconds to allow tissue release. Do not roll over bony prominences. Avoid rolling directly on the lateral knee. The patient may modulate pressure by shifting more weight through the support limbs. This is an adjunct to stretching for iliotibial band syndrome, patellofemoral pain, and lateral knee pain. Contraindicated over areas of acute inflammation, skin breakdown, or anticoagulated patients with bruising risk.', ARRAY['hip', 'knee'], 'beginner', ARRAY['foam roller'], 3, 1, 60, ARRAY['self-myofascial release', 'IT band', 'foam rolling', 'lateral knee', 'flexibility'], true);
