-- Expanded Exercise Library Seed Data
-- Run in Supabase SQL Editor to populate the exercise library
-- These are real clinical PT exercises organized by body region

-- First clear existing seed data to avoid duplicates
-- DELETE FROM exercise_library; -- Uncomment if you want a clean slate

-- ============================================================
-- SHOULDER (15 exercises)
-- ============================================================
INSERT INTO exercise_library (name, description, instructions, body_part, difficulty, equipment, sets, reps, tags, is_active) VALUES
('Pendulum Swings', 'Gentle shoulder mobilization using gravity-assisted motion.', 'Lean forward with uninvolved hand on a table for support. Let the affected arm hang freely. Gently swing the arm in small circles clockwise for 30 seconds, then counterclockwise. Gradually increase circle size as tolerated. Keep the shoulder relaxed — let gravity and momentum do the work.', ARRAY['shoulder'], 'beginner', ARRAY['none'], 3, 15, ARRAY['mobilization', 'warm-up', 'post-surgical'], true),
('Wall Slides', 'Active-assisted shoulder flexion using a wall for support.', 'Stand facing a wall with fingertips touching at chest height. Slowly slide hands up the wall as far as comfortable, keeping elbows slightly bent. Hold at the top for 5 seconds. Slowly slide back down. Do not push through sharp pain.', ARRAY['shoulder'], 'beginner', ARRAY['none'], 3, 10, ARRAY['ROM', 'active-assisted'], true),
('External Rotation with Band', 'Rotator cuff strengthening in external rotation.', 'Stand with elbow bent 90 degrees at your side, holding a resistance band attached to a door handle at elbow height. Keep elbow pinned to your side. Rotate forearm outward away from body. Slowly return to start. Maintain upright posture throughout.', ARRAY['shoulder', 'rotator cuff'], 'intermediate', ARRAY['resistance band'], 3, 12, ARRAY['strengthening', 'rotator cuff'], true),
('Internal Rotation with Band', 'Rotator cuff strengthening in internal rotation.', 'Stand sideways to anchor point with band in the hand closest to the anchor. Elbow bent 90 degrees at your side. Pull band across your body, rotating forearm inward. Slowly return. Keep elbow pinned to your side throughout the movement.', ARRAY['shoulder', 'rotator cuff'], 'intermediate', ARRAY['resistance band'], 3, 12, ARRAY['strengthening', 'rotator cuff'], true),
('Scapular Squeezes', 'Postural exercise to strengthen middle trapezius and rhomboids.', 'Sit or stand with arms at your sides. Squeeze shoulder blades together as if pinching a pencil between them. Hold for 5 seconds. Release slowly. Keep shoulders down away from ears. Focus on the squeeze between the shoulder blades.', ARRAY['shoulder', 'thoracic spine'], 'beginner', ARRAY['none'], 3, 15, ARRAY['postural', 'strengthening'], true),
('Y-T-W Raises (Prone)', 'Scapular stabilization exercise targeting multiple shoulder muscles.', 'Lie face down on a bench or bed with arms hanging. Y: Raise arms overhead in a Y shape with thumbs up, squeeze shoulder blades. T: Raise arms out to sides in a T shape, palms down. W: Pull elbows back and down into a W shape. Hold each position 3 seconds. Lower slowly.', ARRAY['shoulder', 'rotator cuff'], 'intermediate', ARRAY['none'], 3, 8, ARRAY['strengthening', 'scapular stabilization'], true),
('Shoulder Flexion AAROM (Wand)', 'Active-assisted overhead reach using a dowel or wand.', 'Lie on your back holding a wand with both hands shoulder-width apart. Use the uninvolved arm to push the involved arm overhead, assisting the motion. Go as far as comfortable without pain. Hold 5 seconds at end range. Slowly return.', ARRAY['shoulder'], 'beginner', ARRAY['wand', 'dowel'], 3, 10, ARRAY['ROM', 'active-assisted', 'post-surgical'], true),
('Sleeper Stretch', 'Stretches the posterior shoulder capsule to improve internal rotation.', 'Lie on your involved side with the shoulder and elbow both bent to 90 degrees. Use your other hand to gently push the forearm toward the floor, rotating the shoulder internally. Hold 30 seconds. You should feel a stretch in the back of the shoulder. Do not force through pain.', ARRAY['shoulder', 'rotator cuff'], 'intermediate', ARRAY['none'], 3, 3, ARRAY['stretching', 'flexibility', 'posterior capsule'], true),
('Cross-Body Stretch', 'Stretches the posterior deltoid and posterior capsule.', 'Bring your involved arm across your body at shoulder height. Use the opposite hand to gently pull the arm closer to your chest. Hold for 30 seconds. You should feel a comfortable stretch in the back of the shoulder. Keep the shoulder relaxed and down.', ARRAY['shoulder'], 'beginner', ARRAY['none'], 3, 3, ARRAY['stretching', 'flexibility'], true),
('Shoulder Shrugs', 'Strengthens the upper trapezius and levator scapulae.', 'Stand or sit with arms at sides. Raise both shoulders toward your ears as high as possible. Hold 3 seconds at the top. Slowly lower back down. Keep arms relaxed. Can add light dumbbells for progression.', ARRAY['shoulder', 'cervical spine'], 'beginner', ARRAY['none'], 3, 12, ARRAY['strengthening', 'warm-up'], true),
('Lateral Raises', 'Deltoid strengthening for shoulder abduction.', 'Stand with arms at sides holding light weights. Raise arms out to the sides to shoulder height, leading with the elbows. Keep a slight bend in the elbows. Slowly lower back to start. Do not swing or use momentum.', ARRAY['shoulder'], 'intermediate', ARRAY['dumbbells'], 3, 10, ARRAY['strengthening', 'deltoid'], true),
('Prone I-Y-T', 'Progressive scapular stabilization done face down.', 'Lie face down on a bench or stability ball. I: Raise both arms straight overhead (thumbs up). Y: Raise arms at 45 degrees from overhead. T: Raise arms straight out to sides. Hold each 3-5 seconds. Focus on squeezing shoulder blades together.', ARRAY['shoulder', 'rotator cuff'], 'advanced', ARRAY['bench'], 3, 8, ARRAY['strengthening', 'scapular stabilization'], true),
('Empty Can Exercise', 'Targets the supraspinatus muscle of the rotator cuff.', 'Stand holding light weights with arms at sides. Raise arms to 90 degrees in the scapular plane (30 degrees forward from straight out to the side), with thumbs pointing down as if pouring out a can. Hold 3 seconds. Lower slowly. Keep weight light to avoid impingement.', ARRAY['shoulder', 'rotator cuff'], 'intermediate', ARRAY['dumbbells'], 3, 10, ARRAY['strengthening', 'rotator cuff', 'supraspinatus'], true),
('Door Frame Pec Stretch', 'Stretches the pectoralis major and minor.', 'Stand in a doorway with forearms on the door frame at shoulder height, elbows bent 90 degrees. Step one foot forward through the doorway until you feel a stretch across your chest and front of shoulders. Hold 30 seconds. Keep core engaged and do not arch the low back.', ARRAY['shoulder'], 'beginner', ARRAY['doorway'], 3, 3, ARRAY['stretching', 'flexibility', 'postural'], true),
('Resisted Shoulder Extension', 'Strengthens posterior deltoid and latissimus dorsi.', 'Attach resistance band at waist height. Face the anchor, holding the band with arm extended forward. Pull band straight back past your hip, keeping arm straight. Squeeze shoulder blade back and down. Slowly return to start.', ARRAY['shoulder'], 'intermediate', ARRAY['resistance band'], 3, 12, ARRAY['strengthening'], true)
ON CONFLICT DO NOTHING;

-- ============================================================
-- KNEE (12 exercises)
-- ============================================================
INSERT INTO exercise_library (name, description, instructions, body_part, difficulty, equipment, sets, reps, tags, is_active) VALUES
('Quad Sets', 'Isometric quadriceps contraction for early rehab.', 'Sit or lie with your leg straight. Tighten the muscle on top of your thigh by pressing the back of your knee flat into the surface. You should see your kneecap move slightly upward. Hold for 5-10 seconds. Relax completely between reps. Place a rolled towel under the knee for feedback if needed.', ARRAY['knee', 'quadriceps'], 'beginner', ARRAY['none'], 3, 15, ARRAY['isometric', 'post-surgical', 'strengthening'], true),
('Straight Leg Raises', 'Quadriceps strengthening without bending the knee.', 'Lie on your back with the uninvolved knee bent and foot flat. Tighten the quad on the straight leg (lock the knee). Lift the straight leg to the height of the opposite knee. Hold 3 seconds at the top. Lower slowly. Keep the knee locked throughout.', ARRAY['knee', 'quadriceps', 'hip'], 'beginner', ARRAY['none'], 3, 12, ARRAY['strengthening', 'post-surgical'], true),
('Heel Slides', 'Gentle knee flexion ROM exercise.', 'Lie on your back with legs straight. Slowly slide your heel toward your buttock, bending the knee as far as comfortable. Hold at end range for 5 seconds. Slowly slide back out straight. You may use a towel or strap around the foot to assist the motion.', ARRAY['knee'], 'beginner', ARRAY['none'], 3, 10, ARRAY['ROM', 'post-surgical'], true),
('Terminal Knee Extensions', 'Strengthens the quadriceps in the last 30 degrees of extension.', 'Place a rolled towel or foam roller under your knee while sitting or lying. Press the back of your knee into the roll and straighten the knee fully, lifting the foot. Hold 5 seconds at full extension. Lower slowly. This targets the VMO specifically.', ARRAY['knee', 'quadriceps'], 'beginner', ARRAY['towel roll'], 3, 12, ARRAY['strengthening', 'VMO', 'post-surgical'], true),
('Wall Squats (Wall Sits)', 'Closed-chain quadriceps and glute strengthening.', 'Stand with your back against a wall, feet shoulder-width apart and about 18 inches from the wall. Slide down until your knees are bent to about 45-60 degrees (do not go past 90). Hold for 15-30 seconds. Press through your heels to slide back up. Keep knees aligned over ankles.', ARRAY['knee', 'quadriceps', 'glutes'], 'intermediate', ARRAY['wall'], 3, 10, ARRAY['strengthening', 'closed chain'], true),
('Step-Ups', 'Functional strengthening for stairs and daily activities.', 'Stand facing a step (4-8 inches high). Step up with the involved leg, pressing through the heel. Bring the other foot up. Step down with the uninvolved leg first. Keep your knee aligned over your second toe. Use a railing for balance if needed. Increase step height as you progress.', ARRAY['knee', 'quadriceps', 'glutes'], 'intermediate', ARRAY['step'], 3, 10, ARRAY['strengthening', 'functional'], true),
('Hamstring Curls (Standing)', 'Strengthens the hamstrings in a functional position.', 'Stand holding onto a counter or chair for balance. Bend your knee, bringing your heel toward your buttock. Hold 3 seconds at the top. Lower slowly. Keep your thighs parallel — do not let the knee drift forward. Add ankle weights for progression.', ARRAY['knee', 'hamstrings'], 'beginner', ARRAY['none'], 3, 12, ARRAY['strengthening'], true),
('Single Leg Balance', 'Proprioception and balance training.', 'Stand on your involved leg with the knee slightly bent (soft knee). Hold for 30 seconds. Keep your hips level and core engaged. Progress by closing your eyes, standing on a foam pad, or adding arm movements. Use a wall or counter nearby for safety.', ARRAY['knee', 'ankle'], 'beginner', ARRAY['none'], 3, 3, ARRAY['balance', 'proprioception'], true),
('Mini Squats', 'Gentle bilateral squat for early strengthening.', 'Stand with feet shoulder-width apart, holding onto a counter if needed. Bend knees to about 30-45 degrees, sitting back as if sitting in a chair. Keep weight in your heels and knees behind your toes. Hold 3 seconds at the bottom. Stand back up fully.', ARRAY['knee', 'quadriceps', 'glutes'], 'beginner', ARRAY['none'], 3, 12, ARRAY['strengthening', 'closed chain'], true),
('Lateral Step-Downs', 'Eccentric quadriceps control for stairs.', 'Stand on the edge of a step with your involved leg. Slowly lower the opposite foot toward the ground by bending the knee on the step. Lightly tap the heel and return to standing. Move slowly and control the descent. Keep the knee aligned over the second toe.', ARRAY['knee', 'quadriceps'], 'advanced', ARRAY['step'], 3, 10, ARRAY['strengthening', 'eccentric', 'functional'], true),
('Stationary Bike', 'Low-impact cardiovascular exercise and knee ROM.', 'Adjust seat height so your knee is slightly bent at the bottom of the pedal stroke. Start with low resistance. Pedal smoothly for 10-15 minutes. Focus on achieving full pedal circles. Increase resistance and duration as tolerated. If you cannot make full circles, rock the pedals back and forth.', ARRAY['knee'], 'beginner', ARRAY['stationary bike'], 1, 1, ARRAY['cardiovascular', 'ROM', 'warm-up'], true),
('Seated Knee Extension', 'Machine or manual knee extension for quad strength.', 'Sit on a chair with feet flat. Straighten one knee, lifting the foot until the leg is fully extended. Hold 5 seconds. Slowly lower. Add ankle weights for resistance as you progress. Keep the back of the thigh on the chair.', ARRAY['knee', 'quadriceps'], 'intermediate', ARRAY['ankle weights'], 3, 12, ARRAY['strengthening', 'open chain'], true)
ON CONFLICT DO NOTHING;

-- ============================================================
-- HIP (12 exercises)
-- ============================================================
INSERT INTO exercise_library (name, description, instructions, body_part, difficulty, equipment, sets, reps, tags, is_active) VALUES
('Clamshells', 'Targets the gluteus medius for hip stability.', 'Lie on your side with knees bent to 45 degrees and feet together. Keeping feet touching, open the top knee like a clamshell. Raise the knee as high as you can without rotating the pelvis backward. Hold 3 seconds. Lower slowly. Place a resistance band above the knees for progression.', ARRAY['hip', 'glutes'], 'beginner', ARRAY['none'], 3, 15, ARRAY['strengthening', 'glute med'], true),
('Glute Bridges', 'Strengthens glutes and hamstrings in a supine position.', 'Lie on your back with knees bent, feet flat on the floor hip-width apart. Push through your heels to lift your hips toward the ceiling until your body forms a straight line from shoulders to knees. Squeeze your glutes at the top. Hold 3 seconds. Lower slowly. Do not arch your low back.', ARRAY['hip', 'glutes', 'hamstrings'], 'beginner', ARRAY['none'], 3, 12, ARRAY['strengthening', 'glute activation'], true),
('Monster Walks', 'Lateral hip strengthening with resistance band.', 'Place a resistance band around your ankles or just above the knees. Stand in a quarter squat position. Take small steps sideways, leading with the heel. Keep tension on the band throughout. Take 10 steps in one direction, then 10 steps back. Keep toes pointed forward and maintain the squat position.', ARRAY['hip', 'glutes'], 'intermediate', ARRAY['resistance band'], 3, 10, ARRAY['strengthening', 'glute med', 'functional'], true),
('Hip Flexor Stretch (Half-Kneeling)', 'Stretches the iliopsoas and rectus femoris.', 'Kneel on the involved knee with the opposite foot flat on the floor in front. Keep your torso upright and engage your core. Shift your weight forward until you feel a stretch in the front of the hip and thigh of the kneeling leg. Hold 30 seconds. Squeeze the glute on the stretching side for a deeper stretch.', ARRAY['hip'], 'beginner', ARRAY['none'], 3, 3, ARRAY['stretching', 'flexibility', 'hip flexor'], true),
('Side-Lying Hip Abduction', 'Isolates the gluteus medius in side-lying.', 'Lie on your side with bottom knee bent for stability. Keep the top leg straight. Lift the top leg toward the ceiling about 12-18 inches, leading with the heel. Keep the toes pointed slightly downward. Hold 3 seconds. Lower slowly. Do not roll backward.', ARRAY['hip', 'glutes'], 'beginner', ARRAY['none'], 3, 12, ARRAY['strengthening', 'glute med'], true),
('Standing Hip Abduction', 'Hip strengthening in a functional standing position.', 'Stand holding onto a counter for balance. Lift the involved leg out to the side, keeping the knee straight and toes pointed forward. Raise to about 30 degrees. Hold 3 seconds. Lower slowly. Keep your torso upright — do not lean to the opposite side. Add ankle weight for progression.', ARRAY['hip', 'glutes'], 'intermediate', ARRAY['none'], 3, 12, ARRAY['strengthening', 'functional'], true),
('Piriformis Stretch (Figure 4)', 'Stretches the piriformis and deep external rotators.', 'Lie on your back. Cross the involved ankle over the opposite knee to form a figure 4. Reach through and grasp behind the thigh of the bottom leg. Pull the bottom leg toward your chest until you feel a stretch deep in the buttock. Hold 30 seconds. Keep your head and shoulders flat.', ARRAY['hip', 'glutes'], 'beginner', ARRAY['none'], 3, 3, ARRAY['stretching', 'flexibility', 'piriformis'], true),
('Fire Hydrants', 'Hip abduction and external rotation strengthening.', 'Start on hands and knees with hands under shoulders and knees under hips. Keeping the knee bent, lift one leg out to the side like a dog at a fire hydrant. Raise until the thigh is parallel to the floor. Hold 3 seconds. Lower slowly. Keep your core tight and do not shift your weight to the opposite side.', ARRAY['hip', 'glutes'], 'intermediate', ARRAY['none'], 3, 12, ARRAY['strengthening', 'glute med', 'core'], true),
('Single Leg Deadlift', 'Advanced hip hinge for posterior chain and balance.', 'Stand on one leg with a slight knee bend. Hinge forward at the hips while extending the opposite leg behind you. Reach toward the floor with both hands. Your body should form a T shape. Return to standing by squeezing the glute. Keep your back flat throughout.', ARRAY['hip', 'hamstrings', 'glutes'], 'advanced', ARRAY['none'], 3, 8, ARRAY['strengthening', 'balance', 'functional'], true),
('IT Band Foam Roll', 'Self-myofascial release for the iliotibial band.', 'Lie on your side with a foam roller under your outer thigh, just below the hip. Support yourself with your hands and top foot. Roll slowly from the hip to just above the knee, spending 30-60 seconds on tender areas. Avoid rolling directly on the knee or hip bone. Control the pressure with your arms.', ARRAY['hip', 'knee'], 'beginner', ARRAY['foam roller'], 1, 1, ARRAY['mobility', 'self-myofascial release', 'warm-up'], true),
('Hip Circles', 'Dynamic mobility exercise for the hip joint.', 'Stand on one leg holding onto a counter. Make large circles with the free leg — forward, out to the side, behind, and back to start. Perform 10 circles in each direction. Keep your torso stable and the circles controlled. This is a great warm-up exercise.', ARRAY['hip'], 'beginner', ARRAY['none'], 2, 10, ARRAY['mobility', 'warm-up', 'ROM'], true),
('Supine Hip Flexion (Marching)', 'Gentle hip flexor activation in a supported position.', 'Lie on your back with knees bent. Slowly lift one knee toward your chest, keeping the foot relaxed. Lower slowly and repeat on the other side. Alternate legs in a marching pattern. Keep your lower back flat against the surface. This is a gentle early rehab exercise.', ARRAY['hip'], 'beginner', ARRAY['none'], 3, 10, ARRAY['strengthening', 'post-surgical', 'hip flexor'], true)
ON CONFLICT DO NOTHING;

-- ============================================================
-- LUMBAR SPINE (10 exercises)
-- ============================================================
INSERT INTO exercise_library (name, description, instructions, body_part, difficulty, equipment, sets, reps, tags, is_active) VALUES
('Cat-Cow Stretch', 'Spinal mobility exercise alternating flexion and extension.', 'Start on hands and knees. Cow: Let your belly drop toward the floor while lifting your head and tailbone up (extension). Cat: Round your back toward the ceiling, tucking your chin to your chest (flexion). Move slowly between positions, holding each for 3-5 seconds. Breathe in during cow, out during cat.', ARRAY['lumbar spine', 'thoracic spine'], 'beginner', ARRAY['none'], 2, 10, ARRAY['mobility', 'warm-up', 'spinal'], true),
('Bird Dog', 'Core stabilization exercise targeting multifidus and erector spinae.', 'Start on hands and knees with a neutral spine. Simultaneously extend the right arm forward and left leg backward until they are parallel to the floor. Hold 5 seconds, maintaining a stable trunk. Return to start and repeat on the opposite side. Do not let the hips rotate or the back sag.', ARRAY['lumbar spine', 'core'], 'intermediate', ARRAY['none'], 3, 10, ARRAY['core stability', 'strengthening'], true),
('Dead Bug', 'Anti-extension core stability exercise.', 'Lie on your back with arms pointing toward the ceiling and knees bent 90 degrees (tabletop position). Press your lower back flat into the floor. Slowly extend one arm overhead and the opposite leg toward the floor simultaneously. Return to start and repeat on the opposite side. Maintain contact between your lower back and the floor throughout.', ARRAY['lumbar spine', 'core'], 'intermediate', ARRAY['none'], 3, 10, ARRAY['core stability', 'strengthening'], true),
('Pelvic Tilts', 'Foundational exercise for learning lumbar spine control.', 'Lie on your back with knees bent and feet flat. Gently flatten your lower back against the floor by tilting your pelvis backward (pulling your belly button toward your spine). Hold 5 seconds. Release. This is a small, controlled movement — your hips should not lift off the floor.', ARRAY['lumbar spine', 'core'], 'beginner', ARRAY['none'], 3, 15, ARRAY['core activation', 'motor control'], true),
('Prone Press-Up (McKenzie Extension)', 'Lumbar extension exercise for disc-related pain.', 'Lie face down with hands positioned under your shoulders as if doing a push-up. Press your upper body up, straightening your arms while keeping your hips and legs relaxed on the surface. Hold the top position for 2-3 seconds. Lower slowly. Your pelvis should stay on the surface. This should centralize your symptoms.', ARRAY['lumbar spine'], 'beginner', ARRAY['none'], 3, 10, ARRAY['extension', 'McKenzie', 'disc'], true),
('Plank', 'Isometric core endurance exercise.', 'Start in a push-up position on your forearms with elbows under shoulders. Maintain a straight line from your head to your heels. Engage your core, squeeze your glutes, and do not let your hips sag or pike up. Hold for 20-60 seconds. Breathe normally throughout. Progress by increasing hold time.', ARRAY['lumbar spine', 'core'], 'intermediate', ARRAY['none'], 3, 3, ARRAY['core stability', 'endurance', 'isometric'], true),
('Side Plank', 'Lateral core stability exercise targeting the quadratus lumborum and obliques.', 'Lie on your side with your elbow under your shoulder. Lift your hips off the ground, forming a straight line from your head to your feet. Hold for 15-30 seconds. Keep your top hip stacked directly over the bottom hip. Modify by bending the bottom knee. Progress by lifting the top leg.', ARRAY['lumbar spine', 'core'], 'intermediate', ARRAY['none'], 3, 3, ARRAY['core stability', 'lateral', 'obliques'], true),
('Knees-to-Chest Stretch', 'Gentle lumbar flexion stretch.', 'Lie on your back. Bring both knees toward your chest, holding behind your thighs. Gently pull until you feel a comfortable stretch in your lower back. Hold for 30 seconds. Rock gently side to side for additional mobilization. Keep your head and shoulders relaxed on the floor.', ARRAY['lumbar spine'], 'beginner', ARRAY['none'], 3, 3, ARRAY['stretching', 'flexibility', 'flexion'], true),
('Supine Trunk Rotation', 'Gentle rotational mobilization of the lumbar spine.', 'Lie on your back with knees bent and feet flat. Keep your shoulders flat on the floor. Slowly let both knees fall to one side. Hold for 5 seconds. Return to center and repeat on the other side. Move within a pain-free range. Use your core to control the motion.', ARRAY['lumbar spine', 'thoracic spine'], 'beginner', ARRAY['none'], 2, 10, ARRAY['mobility', 'rotation', 'flexibility'], true),
('Child Pose Stretch', 'Gentle full-spine flexion and relaxation stretch.', 'Kneel on the floor. Sit your hips back onto your heels. Reach your arms forward along the floor, lowering your chest toward the ground. Hold for 30-60 seconds. Breathe deeply and relax into the stretch. Walk your hands to one side for a lateral stretch. This stretches the back, hips, and shoulders.', ARRAY['lumbar spine', 'thoracic spine'], 'beginner', ARRAY['none'], 3, 3, ARRAY['stretching', 'flexibility', 'relaxation'], true)
ON CONFLICT DO NOTHING;

-- ============================================================
-- CERVICAL SPINE (8 exercises)
-- ============================================================
INSERT INTO exercise_library (name, description, instructions, body_part, difficulty, equipment, sets, reps, tags, is_active) VALUES
('Chin Tucks', 'Strengthens deep neck flexors and corrects forward head posture.', 'Sit or stand with good posture. Pull your chin straight back, making a double chin. Hold for 5 seconds. You should feel a gentle stretch at the base of your skull and lengthening of the back of your neck. Do not tilt your head up or down. Think of sliding your head backward on a shelf.', ARRAY['cervical spine'], 'beginner', ARRAY['none'], 3, 12, ARRAY['postural', 'strengthening', 'deep neck flexors'], true),
('Upper Trapezius Stretch', 'Stretches the upper trapezius muscle for neck tension relief.', 'Sit with good posture. Tilt your head toward one shoulder (ear to shoulder). Gently apply pressure with the same-side hand on top of your head for a deeper stretch. Hold 30 seconds. You should feel a stretch along the side of the neck. Keep the opposite shoulder down. Do not rotate or tip the head forward.', ARRAY['cervical spine', 'shoulder'], 'beginner', ARRAY['none'], 3, 3, ARRAY['stretching', 'flexibility', 'tension relief'], true),
('Cervical Rotation Stretch', 'Improves rotational range of motion in the neck.', 'Sit with good posture. Slowly turn your head to look over one shoulder as far as comfortable. Hold for 15-20 seconds. Return to center and repeat to the other side. Keep your shoulders relaxed and facing forward. Move slowly and do not force the motion.', ARRAY['cervical spine'], 'beginner', ARRAY['none'], 3, 3, ARRAY['stretching', 'ROM', 'flexibility'], true),
('Levator Scapulae Stretch', 'Targets the levator scapulae muscle — a common source of neck/shoulder pain.', 'Sit with good posture. Turn your head 45 degrees to one side. Tuck your chin toward your armpit on that side. Use the same-side hand to gently assist the stretch. Hold 30 seconds. You should feel a stretch at the back-side of the neck. Keep the opposite shoulder down.', ARRAY['cervical spine', 'shoulder'], 'beginner', ARRAY['none'], 3, 3, ARRAY['stretching', 'flexibility', 'tension relief'], true),
('Isometric Neck Strengthening', 'Strengthens neck muscles in all planes without movement.', 'Sit with good posture. Place your hand on your forehead. Push your head into your hand without moving (resist the motion). Hold 5 seconds. Repeat on each side (place hand on temple) and against the back of the head. Build up to 10-second holds. This strengthens without stressing the joints.', ARRAY['cervical spine'], 'beginner', ARRAY['none'], 3, 8, ARRAY['isometric', 'strengthening'], true),
('Neck Retraction with Extension', 'Combined chin tuck with gentle extension for upper cervical mobility.', 'Start with a chin tuck. Once tucked, slowly extend (look up) keeping the chin retracted. This produces upper cervical extension with lower cervical flexion. Hold 3 seconds at the top. Return to neutral. Do not let the chin poke forward.', ARRAY['cervical spine'], 'intermediate', ARRAY['none'], 3, 10, ARRAY['mobility', 'McKenzie', 'extension'], true),
('Scalene Stretch', 'Stretches the anterior and middle scalene muscles.', 'Sit with one hand grasping the edge of the chair seat. Tilt your head away from the anchored side. Slightly rotate your chin toward the ceiling for anterior scalene. Hold 30 seconds. For middle scalene, keep the head tilted sideways without rotation. Feel the stretch along the front-side of the neck.', ARRAY['cervical spine'], 'intermediate', ARRAY['chair'], 3, 3, ARRAY['stretching', 'flexibility', 'scalene'], true),
('SCM Stretch', 'Stretches the sternocleidomastoid muscle.', 'Sit with good posture. Rotate your head to one side. Then extend your neck (look up toward the ceiling). You should feel a stretch along the front of the neck on the opposite side. Hold for 20-30 seconds. Be gentle — this is a sensitive area. Return slowly to neutral.', ARRAY['cervical spine'], 'beginner', ARRAY['none'], 3, 3, ARRAY['stretching', 'flexibility'], true)
ON CONFLICT DO NOTHING;

-- ============================================================
-- ANKLE & FOOT (8 exercises)
-- ============================================================
INSERT INTO exercise_library (name, description, instructions, body_part, difficulty, equipment, sets, reps, tags, is_active) VALUES
('Ankle Pumps', 'Promotes circulation and early ankle mobility.', 'Sit or lie with legs extended. Pump your ankles by pointing your toes away from you (plantarflexion) then pulling them toward you (dorsiflexion). Move through full range rhythmically. Do 20-30 pumps. This promotes circulation and is ideal for post-surgical or bed-bound patients.', ARRAY['ankle', 'foot'], 'beginner', ARRAY['none'], 3, 20, ARRAY['mobility', 'circulation', 'post-surgical'], true),
('Heel Raises (Calf Raises)', 'Strengthens the gastrocnemius and soleus muscles.', 'Stand holding onto a counter for balance. Rise up onto your toes as high as you can. Hold 3 seconds at the top. Lower slowly (take 3-4 seconds to lower). Progress by doing single-leg or performing on the edge of a step for additional range.', ARRAY['ankle', 'calf'], 'beginner', ARRAY['none'], 3, 15, ARRAY['strengthening', 'functional'], true),
('Towel Scrunches', 'Intrinsic foot muscle strengthening.', 'Sit with feet flat on a towel spread on the floor. Use your toes to scrunch (grip) the towel and pull it toward you. Release and repeat. Perform for 2-3 minutes or until fatigued. This strengthens the small muscles of the foot that support the arch.', ARRAY['foot'], 'beginner', ARRAY['towel'], 3, 15, ARRAY['strengthening', 'arch support', 'intrinsic'], true),
('Alphabet Ankle ROM', 'Dynamic ankle mobility in all planes.', 'Sit with your foot off the edge of a bed or chair. Using your big toe as a pointer, trace the letters of the alphabet in the air. Move from the ankle, not the knee. Go through A-Z. This moves the ankle through all available ranges of motion in a functional pattern.', ARRAY['ankle'], 'beginner', ARRAY['none'], 1, 1, ARRAY['mobility', 'ROM', 'warm-up'], true),
('Resistance Band Ankle Eversion', 'Peroneal strengthening for lateral ankle stability.', 'Sit with legs extended. Loop a resistance band around the outside of your foot, anchored to a fixed point on the inside. Turn your foot outward against the band resistance (eversion). Slowly return. Keep the knee still — move only at the ankle. This strengthens the muscles that prevent ankle sprains.', ARRAY['ankle'], 'intermediate', ARRAY['resistance band'], 3, 12, ARRAY['strengthening', 'peroneal', 'ankle stability'], true),
('Resistance Band Ankle Inversion', 'Tibialis posterior strengthening for medial ankle support.', 'Sit with legs extended. Loop a resistance band around the inside of your foot, anchored to the outside. Turn your foot inward against the band resistance (inversion). Slowly return. Keep the knee still. This supports the medial arch and prevents overpronation.', ARRAY['ankle'], 'intermediate', ARRAY['resistance band'], 3, 12, ARRAY['strengthening', 'ankle stability'], true),
('BAPS Board Balance', 'Dynamic balance and proprioception training.', 'Stand on a balance board with feet shoulder-width apart. Control the board, trying to keep the edges from touching the ground. Progress from both feet to single leg. Try to maintain the board level for 30-60 seconds. This retrains proprioception after ankle sprains.', ARRAY['ankle', 'foot'], 'advanced', ARRAY['balance board'], 3, 3, ARRAY['balance', 'proprioception', 'dynamic'], true),
('Seated Ankle Dorsiflexion Stretch', 'Stretches the Achilles tendon and gastrocnemius.', 'Sit with a towel or strap looped around the ball of your foot. Gently pull the towel toward you, dorsiflexing the ankle until you feel a stretch in the calf. Hold 30 seconds. Keep the knee straight for gastrocnemius, slightly bent for soleus. Do not bounce.', ARRAY['ankle', 'calf'], 'beginner', ARRAY['towel', 'strap'], 3, 3, ARRAY['stretching', 'flexibility', 'Achilles'], true)
ON CONFLICT DO NOTHING;

-- ============================================================
-- CORE & FULL BODY (10 exercises)
-- ============================================================
INSERT INTO exercise_library (name, description, instructions, body_part, difficulty, equipment, sets, reps, tags, is_active) VALUES
('Diaphragmatic Breathing', 'Core activation and relaxation through proper breathing mechanics.', 'Lie on your back with knees bent. Place one hand on your chest and one on your belly. Breathe in through your nose, directing air into your belly (belly hand should rise, chest hand should stay relatively still). Exhale slowly through pursed lips. Practice for 5 minutes. This activates the deep stabilizing system.', ARRAY['core', 'lumbar spine'], 'beginner', ARRAY['none'], 1, 10, ARRAY['breathing', 'core activation', 'relaxation'], true),
('Pallof Press', 'Anti-rotation core stability exercise.', 'Stand perpendicular to a cable machine or band anchor at chest height. Hold the handle at your chest with both hands. Press the handle straight out in front of you. Hold 3 seconds with arms extended. Return to chest. Resist the rotational pull of the band/cable. Keep hips and shoulders square.', ARRAY['core'], 'intermediate', ARRAY['resistance band', 'cable machine'], 3, 10, ARRAY['core stability', 'anti-rotation', 'strengthening'], true),
('Sit-to-Stand', 'Functional exercise for lower body strength and daily activity.', 'Sit on a standard-height chair with feet flat, hip-width apart. Cross your arms over your chest or reach forward. Stand up by pushing through your heels and leaning slightly forward. Stand all the way up. Sit back down slowly and controlled. Progress by lowering the chair height or adding weight.', ARRAY['full body', 'quadriceps', 'glutes'], 'beginner', ARRAY['chair'], 3, 10, ARRAY['functional', 'strengthening', 'ADL'], true),
('Tandem Walking', 'Balance and coordination exercise (heel-to-toe walking).', 'Walk in a straight line placing the heel of one foot directly in front of the toes of the other foot (like walking on a tightrope). Take 20 steps forward. Keep eyes looking ahead, not at your feet. Use a wall or hallway for safety. Progress by walking backward in tandem or adding head turns.', ARRAY['full body'], 'beginner', ARRAY['none'], 3, 20, ARRAY['balance', 'gait training', 'coordination'], true),
('Romanian Deadlift', 'Hip hinge pattern for posterior chain strengthening.', 'Stand with feet hip-width apart, slight knee bend, holding dumbbells in front of thighs. Hinge at the hips, pushing your buttocks backward while lowering the weights along your legs. Go until you feel a stretch in the hamstrings. Return to standing by squeezing the glutes. Keep the back flat and weights close to your legs.', ARRAY['hamstrings', 'glutes', 'lumbar spine'], 'advanced', ARRAY['dumbbells'], 3, 10, ARRAY['strengthening', 'posterior chain', 'hip hinge'], true),
('Swiss Ball Marching', 'Dynamic core stability exercise on an unstable surface.', 'Sit on a Swiss ball with feet flat and knees at 90 degrees. Maintain upright posture. Slowly lift one foot off the ground 2-3 inches, as if marching. Hold 3 seconds. Place it down and lift the other foot. Keep the ball as still as possible throughout. This challenges trunk stability.', ARRAY['core', 'lumbar spine'], 'intermediate', ARRAY['Swiss ball'], 3, 10, ARRAY['core stability', 'balance'], true),
('Farmer Carries', 'Functional grip and core stability during loaded walking.', 'Hold a weight in each hand at your sides (dumbbells, kettlebells, or gallon jugs). Walk 40-50 feet with upright posture. Keep shoulders back and down, core engaged. Walk at a normal pace. The challenge is maintaining posture under load. Increase weight to progress.', ARRAY['full body', 'core'], 'intermediate', ARRAY['dumbbells', 'kettlebells'], 3, 1, ARRAY['functional', 'core stability', 'grip strength'], true),
('Thoracic Foam Roll Extension', 'Thoracic spine mobility using a foam roller.', 'Place a foam roller perpendicular to your spine at the mid-back level. Support your head with your hands. Extend backward over the roller, opening the chest toward the ceiling. Hold 3-5 seconds. Move the roller slightly up or down and repeat at different segments. Avoid rolling the lower back.', ARRAY['thoracic spine'], 'beginner', ARRAY['foam roller'], 2, 10, ARRAY['mobility', 'thoracic extension', 'postural'], true),
('Squat to Overhead Press', 'Compound functional movement for full body strengthening.', 'Hold dumbbells at shoulder height. Squat down to parallel or comfortable depth. Stand up and press the dumbbells overhead in one fluid motion. Lower the weights back to shoulders as you begin the next squat. Keep core engaged and knees tracking over toes throughout.', ARRAY['full body', 'quadriceps', 'shoulder'], 'advanced', ARRAY['dumbbells'], 3, 10, ARRAY['strengthening', 'functional', 'compound'], true),
('TRX Row', 'Upper body pulling exercise using suspension trainer.', 'Hold TRX handles with arms extended, body leaning back at a 45-degree angle. Pull your chest toward the handles by squeezing your shoulder blades together. Keep body straight from head to heels. Slowly lower back to start. Adjust difficulty by changing your body angle — more upright is easier.', ARRAY['shoulder', 'thoracic spine'], 'intermediate', ARRAY['TRX', 'suspension trainer'], 3, 12, ARRAY['strengthening', 'pulling', 'scapular'], true)
ON CONFLICT DO NOTHING;

-- ============================================================
-- WRIST & HAND (6 exercises)
-- ============================================================
INSERT INTO exercise_library (name, description, instructions, body_part, difficulty, equipment, sets, reps, tags, is_active) VALUES
('Wrist Flexion Stretch', 'Stretches the wrist flexor muscles of the forearm.', 'Extend your arm in front of you with the palm facing up. Use the other hand to gently pull the fingers downward and toward you until you feel a stretch along the inside of the forearm. Hold 30 seconds. Do not lock the elbow. This helps with carpal tunnel and medial epicondylitis.', ARRAY['wrist', 'hand'], 'beginner', ARRAY['none'], 3, 3, ARRAY['stretching', 'flexibility', 'carpal tunnel'], true),
('Wrist Extension Stretch', 'Stretches the wrist extensor muscles of the forearm.', 'Extend your arm in front of you with the palm facing down. Use the other hand to gently push the hand downward until you feel a stretch along the top of the forearm. Hold 30 seconds. This helps with lateral epicondylitis (tennis elbow).', ARRAY['wrist', 'hand'], 'beginner', ARRAY['none'], 3, 3, ARRAY['stretching', 'flexibility', 'tennis elbow'], true),
('Grip Strengthening', 'Strengthens the hand and forearm grip muscles.', 'Hold a tennis ball or hand therapy putty in your palm. Squeeze as hard as comfortable. Hold 5 seconds. Release. Repeat with each hand. Progress from a soft ball to a firmer one. Avoid this exercise if you have acute inflammation in the hand or wrist joints.', ARRAY['hand', 'wrist'], 'beginner', ARRAY['tennis ball', 'therapy putty'], 3, 12, ARRAY['strengthening', 'grip'], true),
('Wrist Curls', 'Strengthens the wrist flexor muscles.', 'Sit with your forearm supported on a table or your thigh, wrist and hand hanging off the edge, palm facing up. Hold a light dumbbell. Curl the wrist upward. Lower slowly. Keep the forearm stationary. Start with 1-2 pounds and progress as tolerated.', ARRAY['wrist', 'hand'], 'beginner', ARRAY['dumbbells'], 3, 12, ARRAY['strengthening', 'wrist flexor'], true),
('Finger Tendon Glides', 'Promotes tendon gliding and reduces adhesions in the hand.', 'Start with fingers extended straight. 1) Make a hook fist (bend at the middle and end joints, keep knuckles straight). 2) Make a full fist. 3) Make a tabletop (bend at knuckles, keep fingers straight). 4) Make a straight fist (all joints bent). Hold each position 5 seconds. Repeat the sequence.', ARRAY['hand'], 'beginner', ARRAY['none'], 3, 5, ARRAY['mobility', 'tendon gliding', 'post-surgical'], true),
('Nerve Glide — Median Nerve', 'Mobilizes the median nerve to reduce carpal tunnel symptoms.', 'Stand with arm at your side. 1) Make a fist facing you. 2) Extend fingers, wrist neutral. 3) Extend wrist back. 4) Extend thumb out. 5) Rotate forearm palm up. 6) Gently stretch wrist further with other hand. Hold each position 5 seconds. Move smoothly between positions. Stop if symptoms increase.', ARRAY['wrist', 'hand'], 'intermediate', ARRAY['none'], 3, 5, ARRAY['nerve mobility', 'carpal tunnel', 'neural glide'], true)
ON CONFLICT DO NOTHING;

-- ============================================================
-- ELBOW (4 exercises)
-- ============================================================
INSERT INTO exercise_library (name, description, instructions, body_part, difficulty, equipment, sets, reps, tags, is_active) VALUES
('Eccentric Wrist Extension', 'Eccentric loading for lateral epicondylitis (tennis elbow).', 'Sit with forearm supported, wrist off the edge, palm down, holding a light dumbbell. Use your other hand to help curl the wrist up. Then slowly lower the weight down using only the involved wrist (5-second count down). The eccentric lowering is the therapeutic phase. Start with 1-2 pounds.', ARRAY['elbow', 'wrist'], 'intermediate', ARRAY['dumbbells'], 3, 12, ARRAY['eccentric', 'tennis elbow', 'lateral epicondylitis'], true),
('Forearm Pronation/Supination', 'Restores rotational forearm mobility.', 'Sit with elbow bent 90 degrees at your side. Hold a hammer or weighted object. Slowly rotate your forearm palm up (supination). Then rotate palm down (pronation). Move only at the forearm — keep the elbow still. Use a full range of motion. Can be done with or without weight.', ARRAY['elbow', 'wrist'], 'beginner', ARRAY['hammer', 'dumbbells'], 3, 12, ARRAY['ROM', 'mobility', 'strengthening'], true),
('Bicep Curls', 'Standard elbow flexion strengthening.', 'Stand or sit holding dumbbells with palms facing forward. Curl the weights up toward your shoulders by bending the elbows. Squeeze at the top. Lower slowly. Keep the upper arms stationary and elbows at your sides. Do not swing or use momentum.', ARRAY['elbow'], 'beginner', ARRAY['dumbbells'], 3, 12, ARRAY['strengthening', 'elbow flexion'], true),
('Tricep Extension (Overhead)', 'Strengthens the triceps for elbow extension.', 'Hold a dumbbell with both hands behind your head, elbows bent. Extend the arms, pressing the weight overhead. Lower slowly behind your head. Keep the elbows close to your ears and pointing forward. Start with a light weight.', ARRAY['elbow'], 'intermediate', ARRAY['dumbbells'], 3, 10, ARRAY['strengthening', 'elbow extension', 'triceps'], true)
ON CONFLICT DO NOTHING;

-- ============================================================
-- BALANCE & GAIT (6 exercises)
-- ============================================================
INSERT INTO exercise_library (name, description, instructions, body_part, difficulty, equipment, sets, reps, tags, is_active) VALUES
('Static Single Leg Stance', 'Foundational balance exercise on one leg.', 'Stand near a counter for safety. Lift one foot off the ground and balance on the other leg for 30 seconds. Keep the standing knee slightly bent. Focus your eyes on a fixed point ahead. Progress: close eyes, stand on foam pad, add head turns, add arm movements.', ARRAY['full body'], 'beginner', ARRAY['none'], 3, 3, ARRAY['balance', 'proprioception', 'fall prevention'], true),
('Heel-to-Toe Standing', 'Narrowed base of support balance challenge.', 'Stand with one foot directly in front of the other, heel touching toes (tandem stance). Hold for 30 seconds. Arms out to the sides for balance. Switch which foot is in front. Progress by closing eyes. Stay near a wall for safety.', ARRAY['full body'], 'beginner', ARRAY['none'], 3, 3, ARRAY['balance', 'fall prevention'], true),
('Lateral Weight Shifts', 'Weight transfer exercise for dynamic balance.', 'Stand with feet shoulder-width apart. Slowly shift your weight to the right foot, lifting the left foot slightly. Hold 5 seconds. Shift to the left foot. Keep your trunk upright. Progress by increasing the hold time and lifting the foot higher.', ARRAY['full body', 'hip'], 'beginner', ARRAY['none'], 3, 10, ARRAY['balance', 'weight shifting', 'gait prep'], true),
('Backward Walking', 'Retro-walking for gait retraining and quadriceps activation.', 'Walk backward in a clear hallway, placing each foot directly behind the other. Look over your shoulder periodically for safety. Take normal-length steps. Start slowly. Walk 20-30 feet. Progress by adding a slight incline or resistance band around the ankles.', ARRAY['full body'], 'intermediate', ARRAY['none'], 3, 1, ARRAY['gait training', 'quadriceps', 'balance'], true),
('Obstacle Walking', 'Gait training over obstacles for improved clearance and confidence.', 'Set up 4-5 small obstacles (rolled towels, small cones, shoes) in a line. Walk over each obstacle, lifting your feet higher than normal. Step over without touching the obstacles. Progress by increasing obstacle height or walking speed. Use in a safe environment with handrail access nearby.', ARRAY['full body'], 'intermediate', ARRAY['cones', 'obstacles'], 3, 5, ARRAY['gait training', 'functional', 'fall prevention'], true),
('Timed Up and Go Practice', 'Functional mobility test and training exercise.', 'Sit in a standard-height chair. On go, stand up, walk 10 feet at a comfortable pace, turn around, walk back, and sit down. Practice this movement pattern to improve speed and confidence. Goal is under 12 seconds for community ambulators. Focus on smooth transitions between sit-stand-walk-turn.', ARRAY['full body'], 'beginner', ARRAY['chair'], 3, 3, ARRAY['functional', 'gait training', 'fall prevention', 'outcome measure'], true)
ON CONFLICT DO NOTHING;
