export const BODY_REGIONS = [
  { key: 'shoulder', label: 'Shoulder' },
  { key: 'elbow', label: 'Elbow' },
  { key: 'wrist_hand', label: 'Wrist / Hand' },
  { key: 'cervical', label: 'Cervical Spine' },
  { key: 'thoracic', label: 'Thoracic Spine' },
  { key: 'lumbar', label: 'Lumbar Spine' },
  { key: 'hip', label: 'Hip' },
  { key: 'knee', label: 'Knee' },
  { key: 'ankle_foot', label: 'Ankle / Foot' },
  { key: 'tmj', label: 'TMJ' },
]

// ROM movements per body region — each entry: { movement, normalRange }
export const ROM_TEMPLATES = {
  shoulder: [
    { movement: 'Flexion', normalRange: '0-180°' },
    { movement: 'Extension', normalRange: '0-60°' },
    { movement: 'Abduction', normalRange: '0-180°' },
    { movement: 'Adduction', normalRange: '0-45°' },
    { movement: 'Internal Rotation', normalRange: '0-70°' },
    { movement: 'External Rotation', normalRange: '0-90°' },
  ],
  elbow: [
    { movement: 'Flexion', normalRange: '0-150°' },
    { movement: 'Extension', normalRange: '0°' },
    { movement: 'Supination', normalRange: '0-80°' },
    { movement: 'Pronation', normalRange: '0-80°' },
  ],
  wrist_hand: [
    { movement: 'Wrist Flexion', normalRange: '0-80°' },
    { movement: 'Wrist Extension', normalRange: '0-70°' },
    { movement: 'Radial Deviation', normalRange: '0-20°' },
    { movement: 'Ulnar Deviation', normalRange: '0-30°' },
    { movement: 'Grip Strength (lbs)', normalRange: 'varies' },
  ],
  cervical: [
    { movement: 'Flexion', normalRange: '0-50°' },
    { movement: 'Extension', normalRange: '0-60°' },
    { movement: 'Lateral Flexion R', normalRange: '0-45°' },
    { movement: 'Lateral Flexion L', normalRange: '0-45°' },
    { movement: 'Rotation R', normalRange: '0-80°' },
    { movement: 'Rotation L', normalRange: '0-80°' },
  ],
  thoracic: [
    { movement: 'Flexion', normalRange: '0-50°' },
    { movement: 'Extension', normalRange: '0-25°' },
    { movement: 'Rotation R', normalRange: '0-35°' },
    { movement: 'Rotation L', normalRange: '0-35°' },
    { movement: 'Lateral Flexion R', normalRange: '0-25°' },
    { movement: 'Lateral Flexion L', normalRange: '0-25°' },
  ],
  lumbar: [
    { movement: 'Flexion', normalRange: '0-60°' },
    { movement: 'Extension', normalRange: '0-25°' },
    { movement: 'Lateral Flexion R', normalRange: '0-25°' },
    { movement: 'Lateral Flexion L', normalRange: '0-25°' },
    { movement: 'Rotation R', normalRange: '0-30°' },
    { movement: 'Rotation L', normalRange: '0-30°' },
  ],
  hip: [
    { movement: 'Flexion', normalRange: '0-120°' },
    { movement: 'Extension', normalRange: '0-30°' },
    { movement: 'Abduction', normalRange: '0-45°' },
    { movement: 'Adduction', normalRange: '0-30°' },
    { movement: 'Internal Rotation', normalRange: '0-45°' },
    { movement: 'External Rotation', normalRange: '0-45°' },
  ],
  knee: [
    { movement: 'Flexion', normalRange: '0-135°' },
    { movement: 'Extension', normalRange: '0°' },
  ],
  ankle_foot: [
    { movement: 'Dorsiflexion', normalRange: '0-20°' },
    { movement: 'Plantarflexion', normalRange: '0-50°' },
    { movement: 'Inversion', normalRange: '0-35°' },
    { movement: 'Eversion', normalRange: '0-15°' },
  ],
  tmj: [
    { movement: 'Opening', normalRange: '40-55mm' },
    { movement: 'Lateral Excursion R', normalRange: '10mm' },
    { movement: 'Lateral Excursion L', normalRange: '10mm' },
    { movement: 'Protrusion', normalRange: '5-8mm' },
  ],
}

// MMT muscles per body region — each entry: { muscle }
export const MMT_TEMPLATES = {
  shoulder: [
    { muscle: 'Deltoid (Anterior)' },
    { muscle: 'Deltoid (Middle)' },
    { muscle: 'Deltoid (Posterior)' },
    { muscle: 'Supraspinatus' },
    { muscle: 'Infraspinatus' },
    { muscle: 'Subscapularis' },
    { muscle: 'Teres Minor' },
    { muscle: 'Upper Trapezius' },
    { muscle: 'Middle Trapezius' },
    { muscle: 'Lower Trapezius' },
    { muscle: 'Serratus Anterior' },
    { muscle: 'Rhomboids' },
    { muscle: 'Pectoralis Major' },
    { muscle: 'Latissimus Dorsi' },
    { muscle: 'Biceps' },
    { muscle: 'Triceps' },
  ],
  elbow: [
    { muscle: 'Biceps Brachii' },
    { muscle: 'Brachialis' },
    { muscle: 'Triceps' },
    { muscle: 'Pronator Teres' },
    { muscle: 'Supinator' },
  ],
  wrist_hand: [
    { muscle: 'Wrist Flexors' },
    { muscle: 'Wrist Extensors' },
    { muscle: 'Finger Flexors' },
    { muscle: 'Finger Extensors' },
    { muscle: 'Grip' },
    { muscle: 'Pinch' },
  ],
  cervical: [
    { muscle: 'Cervical Flexors' },
    { muscle: 'Cervical Extensors' },
    { muscle: 'SCM' },
    { muscle: 'Upper Trapezius' },
    { muscle: 'Scalenes' },
    { muscle: 'Deep Neck Flexors' },
  ],
  thoracic: [
    { muscle: 'Thoracic Extensors' },
    { muscle: 'Middle Trapezius' },
    { muscle: 'Lower Trapezius' },
    { muscle: 'Rhomboids' },
  ],
  lumbar: [
    { muscle: 'Trunk Flexors (Abs)' },
    { muscle: 'Trunk Extensors' },
    { muscle: 'Obliques' },
    { muscle: 'Transverse Abdominis' },
    { muscle: 'Quadratus Lumborum' },
  ],
  hip: [
    { muscle: 'Hip Flexors (Iliopsoas)' },
    { muscle: 'Gluteus Maximus' },
    { muscle: 'Gluteus Medius' },
    { muscle: 'Gluteus Minimus' },
    { muscle: 'Hip Adductors' },
    { muscle: 'Piriformis' },
    { muscle: 'Tensor Fasciae Latae' },
  ],
  knee: [
    { muscle: 'Quadriceps' },
    { muscle: 'Hamstrings' },
    { muscle: 'Popliteus' },
  ],
  ankle_foot: [
    { muscle: 'Tibialis Anterior' },
    { muscle: 'Gastrocnemius' },
    { muscle: 'Soleus' },
    { muscle: 'Peroneals' },
    { muscle: 'Tibialis Posterior' },
  ],
  tmj: [
    { muscle: 'Masseter' },
    { muscle: 'Temporalis' },
    { muscle: 'Lateral Pterygoid' },
    { muscle: 'Medial Pterygoid' },
  ],
}

// Special tests per body region — each entry: { test }
export const SPECIAL_TEST_TEMPLATES = {
  shoulder: [
    { test: 'Neer Impingement' },
    { test: 'Hawkins-Kennedy' },
    { test: 'Empty Can (Jobe)' },
    { test: 'Full Can' },
    { test: 'Speed Test' },
    { test: 'Yergason Test' },
    { test: "O'Brien Test" },
    { test: 'Apprehension Test' },
    { test: 'Relocation Test' },
    { test: 'Sulcus Sign' },
    { test: 'Cross-Body Adduction' },
    { test: 'Drop Arm Test' },
    { test: 'Lift-Off Test' },
    { test: 'Belly Press' },
  ],
  elbow: [
    { test: 'Valgus Stress' },
    { test: 'Varus Stress' },
    { test: 'Cozen Test' },
    { test: 'Mill Test' },
    { test: 'Tinel Sign (Elbow)' },
  ],
  wrist_hand: [
    { test: 'Phalen Test' },
    { test: 'Reverse Phalen' },
    { test: 'Tinel Sign (Wrist)' },
    { test: 'Finkelstein Test' },
    { test: 'Grind Test' },
    { test: 'Watson Test' },
  ],
  cervical: [
    { test: 'Spurling Test' },
    { test: 'Distraction Test' },
    { test: 'Upper Limb Tension Test (ULTT)' },
    { test: 'Vertebral Artery Test' },
    { test: 'Sharp-Purser Test' },
    { test: 'Alar Ligament Test' },
  ],
  thoracic: [
    { test: 'Spring Test' },
    { test: 'Slump Test' },
    { test: 'Rib Spring Test' },
    { test: 'Thoracic Rotation (seated)' },
  ],
  lumbar: [
    { test: 'Straight Leg Raise (SLR)' },
    { test: 'Slump Test' },
    { test: 'Prone Instability Test' },
    { test: 'FABER Test' },
    { test: 'Centralization / Peripheralization' },
    { test: 'Repeated Motions (McKenzie)' },
    { test: 'SI Joint Provocation Cluster' },
    { test: 'Gaenslen Test' },
  ],
  hip: [
    { test: 'FABER (Patrick) Test' },
    { test: 'FADIR Test' },
    { test: 'Ober Test' },
    { test: 'Thomas Test' },
    { test: 'Trendelenburg Sign' },
    { test: 'Log Roll Test' },
    { test: 'Scour Test' },
    { test: 'Craig Test' },
  ],
  knee: [
    { test: 'Anterior Drawer' },
    { test: 'Lachman Test' },
    { test: 'Posterior Drawer' },
    { test: 'Valgus Stress (MCL)' },
    { test: 'Varus Stress (LCL)' },
    { test: 'McMurray Test' },
    { test: 'Apley Compression' },
    { test: 'Thessaly Test' },
    { test: 'Patellar Apprehension' },
    { test: 'Clarke Sign' },
    { test: 'Noble Compression (ITB)' },
  ],
  ankle_foot: [
    { test: 'Anterior Drawer (Ankle)' },
    { test: 'Talar Tilt' },
    { test: 'Squeeze Test (syndesmosis)' },
    { test: 'Thompson Test (Achilles)' },
    { test: 'Windlass Test (plantar fascia)' },
    { test: 'Tinel Sign (Tarsal Tunnel)' },
  ],
  tmj: [
    { test: 'Joint Loading (compression)' },
    { test: 'Dynamic Loading' },
    { test: 'Joint Play Assessment' },
    { test: 'Deviation on Opening' },
  ],
}

// MMT grading scale
export const MMT_GRADES = [
  { value: '0', label: '0 — No contraction' },
  { value: '1', label: '1 — Trace' },
  { value: '2-', label: '2- — Poor minus' },
  { value: '2', label: '2 — Poor' },
  { value: '2+', label: '2+ — Poor plus' },
  { value: '3-', label: '3- — Fair minus' },
  { value: '3', label: '3 — Fair' },
  { value: '3+', label: '3+ — Fair plus' },
  { value: '4-', label: '4- — Good minus' },
  { value: '4', label: '4 — Good' },
  { value: '4+', label: '4+ — Good plus' },
  { value: '5', label: '5 — Normal' },
  { value: 'NT', label: 'NT — Not Tested' },
]

// Special test result options
export const SPECIAL_TEST_RESULTS = [
  { value: 'positive', label: 'Positive' },
  { value: 'negative', label: 'Negative' },
  { value: 'equivocal', label: 'Equivocal' },
  { value: 'not_tested', label: 'Not Tested' },
]
